// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worksAudit.proto

package worksAudit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	WorksId              string   `protobuf:"bytes,10,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	Status               int32    `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  int32    `protobuf:"varint,11,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Response struct {
	Data                 []*Response_Notify `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32              `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32              `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []*Response_Notify {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *Response) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Response_Notify struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventId              string   `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Title                string   `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Notify) Reset()         { *m = Response_Notify{} }
func (m *Response_Notify) String() string { return proto.CompactTextString(m) }
func (*Response_Notify) ProtoMessage()    {}
func (*Response_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{1, 0}
}

func (m *Response_Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Notify.Unmarshal(m, b)
}
func (m *Response_Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Notify.Marshal(b, m, deterministic)
}
func (m *Response_Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Notify.Merge(m, src)
}
func (m *Response_Notify) XXX_Size() int {
	return xxx_messageInfo_Response_Notify.Size(m)
}
func (m *Response_Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Notify proto.InternalMessageInfo

func (m *Response_Notify) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response_Notify) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Response_Notify) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Response_Notify) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response_Notify) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Response_Notify) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Response_Notify) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Response_Notify) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Response_Notify) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Response_Notify) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type WorksResponse struct {
	Data                 []*WorksResponse_Notify `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32                   `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32                   `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WorksResponse) Reset()         { *m = WorksResponse{} }
func (m *WorksResponse) String() string { return proto.CompactTextString(m) }
func (*WorksResponse) ProtoMessage()    {}
func (*WorksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{2}
}

func (m *WorksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorksResponse.Unmarshal(m, b)
}
func (m *WorksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorksResponse.Marshal(b, m, deterministic)
}
func (m *WorksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorksResponse.Merge(m, src)
}
func (m *WorksResponse) XXX_Size() int {
	return xxx_messageInfo_WorksResponse.Size(m)
}
func (m *WorksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorksResponse proto.InternalMessageInfo

func (m *WorksResponse) GetData() []*WorksResponse_Notify {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WorksResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *WorksResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type WorksResponse_Notify struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorksId              string   `protobuf:"bytes,2,opt,name=worksId,proto3" json:"worksId,omitempty"`
	Uid                  int32    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Comment              string   `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Thumb                string   `protobuf:"bytes,7,opt,name=thumb,proto3" json:"thumb,omitempty"`
	FirstImg             string   `protobuf:"bytes,8,opt,name=firstImg,proto3" json:"firstImg,omitempty"`
	Version              string   `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	EditorVersion        string   `protobuf:"bytes,10,opt,name=editorVersion,proto3" json:"editorVersion,omitempty"`
	TemplateId           string   `protobuf:"bytes,11,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ParentEventId        string   `protobuf:"bytes,12,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	Identity             int32    `protobuf:"varint,13,opt,name=identity,proto3" json:"identity,omitempty"`
	Category             int32    `protobuf:"varint,14,opt,name=category,proto3" json:"category,omitempty"`
	SizeId               int32    `protobuf:"varint,15,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	SecondaryCategory    int32    `protobuf:"varint,16,opt,name=secondary_category,json=secondaryCategory,proto3" json:"secondary_category,omitempty"`
	PageWidth            int32    `protobuf:"varint,20,opt,name=page_width,json=pageWidth,proto3" json:"page_width,omitempty"`
	PageHeight           int32    `protobuf:"varint,17,opt,name=page_height,json=pageHeight,proto3" json:"page_height,omitempty"`
	OtherProperty        string   `protobuf:"bytes,18,opt,name=other_property,json=otherProperty,proto3" json:"other_property,omitempty"`
	SuiteAppType         int32    `protobuf:"varint,21,opt,name=SuiteAppType,proto3" json:"SuiteAppType,omitempty"`
	CreateDevice         int32    `protobuf:"varint,22,opt,name=CreateDevice,proto3" json:"CreateDevice,omitempty"`
	UpdateDevice         int32    `protobuf:"varint,23,opt,name=UpdateDevice,proto3" json:"UpdateDevice,omitempty"`
	CreateSite           int32    `protobuf:"varint,24,opt,name=CreateSite,proto3" json:"CreateSite,omitempty"`
	CreateTime           int32    `protobuf:"varint,25,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int32    `protobuf:"varint,26,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	IsDelete             string   `protobuf:"bytes,27,opt,name=IsDelete,proto3" json:"IsDelete,omitempty"`
	IsBoughtTemplate     string   `protobuf:"bytes,28,opt,name=IsBoughtTemplate,proto3" json:"IsBoughtTemplate,omitempty"`
	IsUsedLocalFonts     string   `protobuf:"bytes,29,opt,name=IsUsedLocalFonts,proto3" json:"IsUsedLocalFonts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorksResponse_Notify) Reset()         { *m = WorksResponse_Notify{} }
func (m *WorksResponse_Notify) String() string { return proto.CompactTextString(m) }
func (*WorksResponse_Notify) ProtoMessage()    {}
func (*WorksResponse_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{2, 0}
}

func (m *WorksResponse_Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorksResponse_Notify.Unmarshal(m, b)
}
func (m *WorksResponse_Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorksResponse_Notify.Marshal(b, m, deterministic)
}
func (m *WorksResponse_Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorksResponse_Notify.Merge(m, src)
}
func (m *WorksResponse_Notify) XXX_Size() int {
	return xxx_messageInfo_WorksResponse_Notify.Size(m)
}
func (m *WorksResponse_Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_WorksResponse_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_WorksResponse_Notify proto.InternalMessageInfo

func (m *WorksResponse_Notify) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WorksResponse_Notify) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *WorksResponse_Notify) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *WorksResponse_Notify) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *WorksResponse_Notify) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *WorksResponse_Notify) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *WorksResponse_Notify) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

func (m *WorksResponse_Notify) GetFirstImg() string {
	if m != nil {
		return m.FirstImg
	}
	return ""
}

func (m *WorksResponse_Notify) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *WorksResponse_Notify) GetEditorVersion() string {
	if m != nil {
		return m.EditorVersion
	}
	return ""
}

func (m *WorksResponse_Notify) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *WorksResponse_Notify) GetParentEventId() string {
	if m != nil {
		return m.ParentEventId
	}
	return ""
}

func (m *WorksResponse_Notify) GetIdentity() int32 {
	if m != nil {
		return m.Identity
	}
	return 0
}

func (m *WorksResponse_Notify) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *WorksResponse_Notify) GetSizeId() int32 {
	if m != nil {
		return m.SizeId
	}
	return 0
}

func (m *WorksResponse_Notify) GetSecondaryCategory() int32 {
	if m != nil {
		return m.SecondaryCategory
	}
	return 0
}

func (m *WorksResponse_Notify) GetPageWidth() int32 {
	if m != nil {
		return m.PageWidth
	}
	return 0
}

func (m *WorksResponse_Notify) GetPageHeight() int32 {
	if m != nil {
		return m.PageHeight
	}
	return 0
}

func (m *WorksResponse_Notify) GetOtherProperty() string {
	if m != nil {
		return m.OtherProperty
	}
	return ""
}

func (m *WorksResponse_Notify) GetSuiteAppType() int32 {
	if m != nil {
		return m.SuiteAppType
	}
	return 0
}

func (m *WorksResponse_Notify) GetCreateDevice() int32 {
	if m != nil {
		return m.CreateDevice
	}
	return 0
}

func (m *WorksResponse_Notify) GetUpdateDevice() int32 {
	if m != nil {
		return m.UpdateDevice
	}
	return 0
}

func (m *WorksResponse_Notify) GetCreateSite() int32 {
	if m != nil {
		return m.CreateSite
	}
	return 0
}

func (m *WorksResponse_Notify) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *WorksResponse_Notify) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *WorksResponse_Notify) GetIsDelete() string {
	if m != nil {
		return m.IsDelete
	}
	return ""
}

func (m *WorksResponse_Notify) GetIsBoughtTemplate() string {
	if m != nil {
		return m.IsBoughtTemplate
	}
	return ""
}

func (m *WorksResponse_Notify) GetIsUsedLocalFonts() string {
	if m != nil {
		return m.IsUsedLocalFonts
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_Notify)(nil), "Response.Notify")
	proto.RegisterType((*WorksResponse)(nil), "WorksResponse")
	proto.RegisterType((*WorksResponse_Notify)(nil), "WorksResponse.Notify")
}

func init() { proto.RegisterFile("worksAudit.proto", fileDescriptor_2de297fef73caeca) }

var fileDescriptor_2de297fef73caeca = []byte{
	// 805 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xde, 0xdc, 0xe3, 0xd3, 0xcb, 0x66, 0x47, 0x7b, 0x99, 0xcd, 0xd2, 0x52, 0x45, 0x05, 0x75,
	0x91, 0xc8, 0x43, 0xf9, 0x05, 0xcb, 0x16, 0x44, 0x24, 0x84, 0x90, 0xdb, 0xd2, 0xc7, 0xc8, 0x9b,
	0x39, 0x4d, 0x46, 0xc4, 0x1e, 0xaf, 0xe7, 0xb8, 0x25, 0x7d, 0xe2, 0x07, 0xf1, 0xbf, 0x78, 0x42,
	0xe2, 0x27, 0xa0, 0x39, 0x33, 0x76, 0x62, 0x56, 0x7d, 0x83, 0xa7, 0xf8, 0xbb, 0xcc, 0x89, 0xcf,
	0x6d, 0x0c, 0xa3, 0x7b, 0x53, 0xfc, 0x6a, 0xdf, 0x95, 0x4a, 0xd3, 0x34, 0x2f, 0x0c, 0x99, 0xc9,
	0x1f, 0x6d, 0x18, 0xc4, 0xf8, 0xb1, 0x44, 0x4b, 0x42, 0x40, 0x37, 0x4b, 0x52, 0x94, 0xad, 0x93,
	0xd6, 0x59, 0x14, 0xf3, 0xb3, 0xe3, 0x68, 0x93, 0xa3, 0x6c, 0x7b, 0xce, 0x3d, 0x8b, 0xe7, 0xd0,
	0xbb, 0x4b, 0xd6, 0x25, 0xca, 0x0e, 0x93, 0x1e, 0x88, 0xcf, 0x61, 0x6f, 0x51, 0x60, 0x42, 0x38,
	0x27, 0x9d, 0xa2, 0xec, 0xb2, 0x06, 0x9e, 0xba, 0xd2, 0x29, 0x1b, 0xca, 0x5c, 0xd5, 0x86, 0x9e,
	0x37, 0x78, 0x8a, 0x0d, 0x6f, 0x20, 0xd2, 0x76, 0xae, 0x70, 0x8d, 0x84, 0xb2, 0x7f, 0xd2, 0x3a,
	0xeb, 0xc5, 0x43, 0x6d, 0x2f, 0x18, 0xbb, 0x17, 0xc9, 0x93, 0x25, 0xca, 0x01, 0xf3, 0xfc, 0xec,
	0x0e, 0xb8, 0xdf, 0xb9, 0xd5, 0x0f, 0x28, 0x87, 0xfe, 0x80, 0x23, 0x2e, 0xf5, 0x03, 0x8a, 0x43,
	0x68, 0x6b, 0x25, 0x23, 0x66, 0xdb, 0x5a, 0x89, 0xd7, 0x30, 0xe4, 0xec, 0xe7, 0x5a, 0x49, 0xe0,
	0xff, 0x1e, 0x30, 0x9e, 0x29, 0xf1, 0x12, 0xfa, 0x96, 0x12, 0x2a, 0xad, 0xdc, 0x67, 0x7b, 0x40,
	0x62, 0x04, 0x9d, 0x52, 0x2b, 0xb9, 0xc7, 0xa4, 0x7b, 0x9c, 0xfc, 0xd5, 0x86, 0x61, 0x8c, 0x36,
	0x37, 0x99, 0x45, 0x71, 0x0a, 0x5d, 0x95, 0x50, 0x22, 0xf7, 0x4f, 0x3a, 0x67, 0x7b, 0xe7, 0xa3,
	0x69, 0x25, 0x4c, 0x7f, 0x32, 0xa4, 0x6f, 0x37, 0x31, 0xab, 0x62, 0x02, 0xfb, 0xc9, 0xed, 0x2d,
	0x2e, 0x08, 0x55, 0x6c, 0xee, 0x6d, 0x88, 0xd6, 0xe0, 0x5c, 0x45, 0xc9, 0x50, 0xb2, 0x96, 0x07,
	0x2c, 0x7a, 0x30, 0xfe, 0xbd, 0x0d, 0x7d, 0x1f, 0xea, 0x93, 0x64, 0xc2, 0x9b, 0xb5, 0xea, 0x37,
	0x73, 0xe9, 0xe1, 0x1d, 0x66, 0xe4, 0xd2, 0xf3, 0xcd, 0x1a, 0x30, 0x6e, 0xa4, 0x37, 0x60, 0xa1,
	0x4a, 0xaf, 0xea, 0x6d, 0x67, 0xa7, 0xb7, 0xff, 0x73, 0x17, 0x5d, 0xa2, 0x9a, 0xd6, 0x18, 0x3a,
	0xe0, 0x81, 0x90, 0x30, 0x58, 0x98, 0x8c, 0x30, 0x23, 0xae, 0x4e, 0x14, 0x57, 0x70, 0xf2, 0xe7,
	0x00, 0x0e, 0x6e, 0x5c, 0x97, 0xea, 0xa2, 0xbf, 0x6d, 0x14, 0xfd, 0xc5, 0xb4, 0xa1, 0xfe, 0x57,
	0x95, 0xff, 0xbb, 0xff, 0xaf, 0xca, 0xb7, 0xea, 0xca, 0x4b, 0xa8, 0xc6, 0xa6, 0x2a, 0x73, 0x35,
	0x45, 0xa1, 0x27, 0x9d, 0x6d, 0x4f, 0xea, 0x6c, 0xbb, 0x8f, 0x64, 0xdb, 0x6b, 0x64, 0xeb, 0x95,
	0x34, 0x75, 0x4a, 0xbf, 0x52, 0x18, 0x72, 0xa4, 0x55, 0x99, 0x7e, 0x08, 0x1d, 0xf4, 0x40, 0x8c,
	0x61, 0x78, 0xab, 0x0b, 0x4b, 0xb3, 0x74, 0xc9, 0xe3, 0x1f, 0xc5, 0x35, 0x76, 0xb1, 0xee, 0xb0,
	0xb0, 0xda, 0x64, 0x3c, 0x36, 0x51, 0x5c, 0x41, 0x71, 0x0a, 0x07, 0xa8, 0x34, 0x99, 0xe2, 0x97,
	0xa0, 0xfb, 0x5e, 0x34, 0x49, 0xd7, 0x67, 0xc2, 0x34, 0x5f, 0xbb, 0x4e, 0x87, 0x1d, 0x88, 0x62,
	0xa8, 0xa8, 0x99, 0x12, 0x5f, 0xc2, 0xd3, 0x3c, 0x29, 0xdc, 0xc4, 0xd5, 0x73, 0xb7, 0xef, 0x03,
	0x79, 0xfa, 0xbb, 0x30, 0x7d, 0x63, 0x18, 0x6a, 0x85, 0x19, 0x69, 0xda, 0x84, 0x22, 0xd7, 0xd8,
	0x69, 0x8b, 0x84, 0x70, 0x69, 0x8a, 0x8d, 0x3c, 0xf4, 0x5a, 0x85, 0xc5, 0x2b, 0x18, 0xb8, 0xbd,
	0x76, 0x71, 0x9f, 0x86, 0xad, 0xd4, 0x0f, 0xee, 0x8f, 0xbf, 0x06, 0x61, 0x71, 0x61, 0x32, 0x95,
	0x14, 0x9b, 0x79, 0x7d, 0x7c, 0xc4, 0x9e, 0x67, 0xb5, 0xf2, 0xbe, 0x8a, 0x73, 0x04, 0xc0, 0x97,
	0xc4, 0xbd, 0x56, 0xb4, 0x92, 0xcf, 0xd9, 0xc6, 0xd7, 0xc6, 0x8d, 0x23, 0x5c, 0x9e, 0x2c, 0xaf,
	0x50, 0x2f, 0x57, 0x24, 0x9f, 0xb1, 0xce, 0x27, 0x7e, 0x60, 0x46, 0x7c, 0x01, 0x87, 0x86, 0x56,
	0x58, 0xcc, 0xf3, 0xc2, 0xe4, 0x58, 0xd0, 0x46, 0x0a, 0x9f, 0x26, 0xb3, 0x3f, 0x07, 0xd2, 0x0d,
	0xdb, 0x65, 0xa9, 0x09, 0xdf, 0xe5, 0xf9, 0x95, 0x5b, 0xaa, 0x17, 0x7e, 0xd8, 0x76, 0x39, 0xe7,
	0x79, 0xcf, 0x9b, 0x74, 0x81, 0x77, 0x7a, 0x81, 0xf2, 0xa5, 0xf7, 0xec, 0x72, 0xce, 0x73, 0xcd,
	0xcb, 0x14, 0x3c, 0xaf, 0xbc, 0x67, 0x97, 0x13, 0xc7, 0x00, 0xfe, 0xcc, 0xa5, 0x26, 0x94, 0xd2,
	0xbf, 0xf2, 0x96, 0xd9, 0xea, 0x6e, 0x21, 0xe5, 0xeb, 0x5d, 0x9d, 0x57, 0xf4, 0x18, 0xe0, 0xba,
	0x5e, 0x58, 0x39, 0xf6, 0xfa, 0x96, 0x71, 0x6d, 0x99, 0x85, 0x8d, 0x95, 0x6f, 0xfc, 0x5c, 0x55,
	0x58, 0x7c, 0x05, 0xa3, 0x99, 0xfd, 0xd6, 0x94, 0xcb, 0x15, 0x5d, 0x85, 0x61, 0x90, 0x9f, 0xb1,
	0xe7, 0x13, 0xde, 0x7b, 0xaf, 0x2d, 0xaa, 0x1f, 0xcd, 0x22, 0x59, 0x7f, 0x6f, 0x32, 0xb2, 0xf2,
	0xa8, 0xf2, 0x36, 0xf9, 0xf3, 0x8f, 0x00, 0x37, 0xf5, 0xc7, 0x49, 0x1c, 0x41, 0xf7, 0x72, 0x65,
	0xee, 0xc5, 0x70, 0x1a, 0x3e, 0x4e, 0xe3, 0xa8, 0xbe, 0x5e, 0x27, 0x4f, 0xc4, 0x31, 0xf4, 0x66,
	0x99, 0xc2, 0xdf, 0x1e, 0xd3, 0x4f, 0x61, 0x8f, 0x83, 0xf9, 0x9c, 0x1e, 0x71, 0x9d, 0x9f, 0x43,
	0x8f, 0x5d, 0xe2, 0x6d, 0xb0, 0x5f, 0x20, 0x25, 0x7a, 0xbd, 0x63, 0x3f, 0x6c, 0x5e, 0x2f, 0x93,
	0x27, 0x1f, 0xfa, 0xfc, 0xd9, 0xfc, 0xe6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x7d, 0xe8,
	0xe6, 0x4a, 0x07, 0x00, 0x00,
}
