// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: worksAudit.proto

/*
Package worksAudit is a generated protocol buffer package.

It is generated from these files:
	worksAudit.proto

It has these top-level messages:
	WorksIndexRequest
	Request
	Response
	ShowResponse
	WorksResponse
	WorksIndexResponse
	WorksDetailResponse
	AuditBracket
	WorksBracket
	DailyPvUvBracket
	DailyRequest
	DailyResponse
	DailyIndexResponse
*/
package worksAudit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for WorksAudit service

type WorksAuditService interface {
	Show(ctx context.Context, in *Request, opts ...client.CallOption) (*ShowResponse, error)
	Index(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	WorksUpdate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AuditUpdate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type worksAuditService struct {
	c    client.Client
	name string
}

func NewWorksAuditService(name string, c client.Client) WorksAuditService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "worksAudit"
	}
	return &worksAuditService{
		c:    c,
		name: name,
	}
}

func (c *worksAuditService) Show(ctx context.Context, in *Request, opts ...client.CallOption) (*ShowResponse, error) {
	req := c.c.NewRequest(c.name, "WorksAudit.Show", in)
	out := new(ShowResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksAuditService) Index(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WorksAudit.Index", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksAuditService) WorksUpdate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WorksAudit.WorksUpdate", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksAuditService) AuditUpdate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WorksAudit.AuditUpdate", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorksAudit service

type WorksAuditHandler interface {
	Show(context.Context, *Request, *ShowResponse) error
	Index(context.Context, *Request, *Response) error
	WorksUpdate(context.Context, *Request, *Response) error
	AuditUpdate(context.Context, *Request, *Response) error
}

func RegisterWorksAuditHandler(s server.Server, hdlr WorksAuditHandler, opts ...server.HandlerOption) error {
	type worksAudit interface {
		Show(ctx context.Context, in *Request, out *ShowResponse) error
		Index(ctx context.Context, in *Request, out *Response) error
		WorksUpdate(ctx context.Context, in *Request, out *Response) error
		AuditUpdate(ctx context.Context, in *Request, out *Response) error
	}
	type WorksAudit struct {
		worksAudit
	}
	h := &worksAuditHandler{hdlr}
	return s.Handle(s.NewHandler(&WorksAudit{h}, opts...))
}

type worksAuditHandler struct {
	WorksAuditHandler
}

func (h *worksAuditHandler) Show(ctx context.Context, in *Request, out *ShowResponse) error {
	return h.WorksAuditHandler.Show(ctx, in, out)
}

func (h *worksAuditHandler) Index(ctx context.Context, in *Request, out *Response) error {
	return h.WorksAuditHandler.Index(ctx, in, out)
}

func (h *worksAuditHandler) WorksUpdate(ctx context.Context, in *Request, out *Response) error {
	return h.WorksAuditHandler.WorksUpdate(ctx, in, out)
}

func (h *worksAuditHandler) AuditUpdate(ctx context.Context, in *Request, out *Response) error {
	return h.WorksAuditHandler.AuditUpdate(ctx, in, out)
}

// Client API for Works service

type WorksService interface {
	WorksDetail(ctx context.Context, in *Request, opts ...client.CallOption) (*WorksDetailResponse, error)
	WorksIndex(ctx context.Context, in *WorksIndexRequest, opts ...client.CallOption) (*WorksIndexResponse, error)
}

type worksService struct {
	c    client.Client
	name string
}

func NewWorksService(name string, c client.Client) WorksService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "worksAudit"
	}
	return &worksService{
		c:    c,
		name: name,
	}
}

func (c *worksService) WorksDetail(ctx context.Context, in *Request, opts ...client.CallOption) (*WorksDetailResponse, error) {
	req := c.c.NewRequest(c.name, "Works.WorksDetail", in)
	out := new(WorksDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worksService) WorksIndex(ctx context.Context, in *WorksIndexRequest, opts ...client.CallOption) (*WorksIndexResponse, error) {
	req := c.c.NewRequest(c.name, "Works.WorksIndex", in)
	out := new(WorksIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Works service

type WorksHandler interface {
	WorksDetail(context.Context, *Request, *WorksDetailResponse) error
	WorksIndex(context.Context, *WorksIndexRequest, *WorksIndexResponse) error
}

func RegisterWorksHandler(s server.Server, hdlr WorksHandler, opts ...server.HandlerOption) error {
	type works interface {
		WorksDetail(ctx context.Context, in *Request, out *WorksDetailResponse) error
		WorksIndex(ctx context.Context, in *WorksIndexRequest, out *WorksIndexResponse) error
	}
	type Works struct {
		works
	}
	h := &worksHandler{hdlr}
	return s.Handle(s.NewHandler(&Works{h}, opts...))
}

type worksHandler struct {
	WorksHandler
}

func (h *worksHandler) WorksDetail(ctx context.Context, in *Request, out *WorksDetailResponse) error {
	return h.WorksHandler.WorksDetail(ctx, in, out)
}

func (h *worksHandler) WorksIndex(ctx context.Context, in *WorksIndexRequest, out *WorksIndexResponse) error {
	return h.WorksHandler.WorksIndex(ctx, in, out)
}

// Client API for DailyPvUv service

type DailyPvUvService interface {
	Show(ctx context.Context, in *DailyRequest, opts ...client.CallOption) (*DailyResponse, error)
	Index(ctx context.Context, in *DailyRequest, opts ...client.CallOption) (*DailyIndexResponse, error)
}

type dailyPvUvService struct {
	c    client.Client
	name string
}

func NewDailyPvUvService(name string, c client.Client) DailyPvUvService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "worksAudit"
	}
	return &dailyPvUvService{
		c:    c,
		name: name,
	}
}

func (c *dailyPvUvService) Show(ctx context.Context, in *DailyRequest, opts ...client.CallOption) (*DailyResponse, error) {
	req := c.c.NewRequest(c.name, "DailyPvUv.Show", in)
	out := new(DailyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyPvUvService) Index(ctx context.Context, in *DailyRequest, opts ...client.CallOption) (*DailyIndexResponse, error) {
	req := c.c.NewRequest(c.name, "DailyPvUv.Index", in)
	out := new(DailyIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DailyPvUv service

type DailyPvUvHandler interface {
	Show(context.Context, *DailyRequest, *DailyResponse) error
	Index(context.Context, *DailyRequest, *DailyIndexResponse) error
}

func RegisterDailyPvUvHandler(s server.Server, hdlr DailyPvUvHandler, opts ...server.HandlerOption) error {
	type dailyPvUv interface {
		Show(ctx context.Context, in *DailyRequest, out *DailyResponse) error
		Index(ctx context.Context, in *DailyRequest, out *DailyIndexResponse) error
	}
	type DailyPvUv struct {
		dailyPvUv
	}
	h := &dailyPvUvHandler{hdlr}
	return s.Handle(s.NewHandler(&DailyPvUv{h}, opts...))
}

type dailyPvUvHandler struct {
	DailyPvUvHandler
}

func (h *dailyPvUvHandler) Show(ctx context.Context, in *DailyRequest, out *DailyResponse) error {
	return h.DailyPvUvHandler.Show(ctx, in, out)
}

func (h *dailyPvUvHandler) Index(ctx context.Context, in *DailyRequest, out *DailyIndexResponse) error {
	return h.DailyPvUvHandler.Index(ctx, in, out)
}
