// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worksAudit.proto

package worksAudit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	WorksId              string   `protobuf:"bytes,10,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	Status               int32    `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  int32    `protobuf:"varint,11,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason               string   `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	AuditStatus          []int32  `protobuf:"varint,14,rep,packed,name=AuditStatus,proto3" json:"AuditStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Request) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Request) GetAuditStatus() []int32 {
	if m != nil {
		return m.AuditStatus
	}
	return nil
}

type ShowResponse struct {
	Data                 *AuditBracket `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32         `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32         `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{1}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

func (m *ShowResponse) GetData() *AuditBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ShowResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *ShowResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Response struct {
	Data                 []*AuditBracket `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32           `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32           `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []*AuditBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *Response) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type WorksResponse struct {
	Data                 []*WorksBracket `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32           `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32           `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WorksResponse) Reset()         { *m = WorksResponse{} }
func (m *WorksResponse) String() string { return proto.CompactTextString(m) }
func (*WorksResponse) ProtoMessage()    {}
func (*WorksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{3}
}

func (m *WorksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorksResponse.Unmarshal(m, b)
}
func (m *WorksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorksResponse.Marshal(b, m, deterministic)
}
func (m *WorksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorksResponse.Merge(m, src)
}
func (m *WorksResponse) XXX_Size() int {
	return xxx_messageInfo_WorksResponse.Size(m)
}
func (m *WorksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorksResponse proto.InternalMessageInfo

func (m *WorksResponse) GetData() []*WorksBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WorksResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *WorksResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type WorksDetailResponse struct {
	Data                 *WorksBracket `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32         `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32         `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WorksDetailResponse) Reset()         { *m = WorksDetailResponse{} }
func (m *WorksDetailResponse) String() string { return proto.CompactTextString(m) }
func (*WorksDetailResponse) ProtoMessage()    {}
func (*WorksDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{4}
}

func (m *WorksDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorksDetailResponse.Unmarshal(m, b)
}
func (m *WorksDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorksDetailResponse.Marshal(b, m, deterministic)
}
func (m *WorksDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorksDetailResponse.Merge(m, src)
}
func (m *WorksDetailResponse) XXX_Size() int {
	return xxx_messageInfo_WorksDetailResponse.Size(m)
}
func (m *WorksDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorksDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorksDetailResponse proto.InternalMessageInfo

func (m *WorksDetailResponse) GetData() *WorksBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WorksDetailResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *WorksDetailResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AuditBracket struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventId              string   `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Title                string   `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditBracket) Reset()         { *m = AuditBracket{} }
func (m *AuditBracket) String() string { return proto.CompactTextString(m) }
func (*AuditBracket) ProtoMessage()    {}
func (*AuditBracket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{5}
}

func (m *AuditBracket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditBracket.Unmarshal(m, b)
}
func (m *AuditBracket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditBracket.Marshal(b, m, deterministic)
}
func (m *AuditBracket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditBracket.Merge(m, src)
}
func (m *AuditBracket) XXX_Size() int {
	return xxx_messageInfo_AuditBracket.Size(m)
}
func (m *AuditBracket) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditBracket.DiscardUnknown(m)
}

var xxx_messageInfo_AuditBracket proto.InternalMessageInfo

func (m *AuditBracket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuditBracket) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuditBracket) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *AuditBracket) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AuditBracket) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuditBracket) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AuditBracket) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *AuditBracket) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *AuditBracket) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AuditBracket) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type WorksBracket struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorksId              string   `protobuf:"bytes,2,opt,name=worksId,proto3" json:"worksId,omitempty"`
	Uid                  int32    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Comment              string   `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Thumb                string   `protobuf:"bytes,7,opt,name=thumb,proto3" json:"thumb,omitempty"`
	FirstImg             string   `protobuf:"bytes,8,opt,name=firstImg,proto3" json:"firstImg,omitempty"`
	Version              string   `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	EditorVersion        string   `protobuf:"bytes,10,opt,name=editorVersion,proto3" json:"editorVersion,omitempty"`
	TemplateId           string   `protobuf:"bytes,11,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ParentEventId        string   `protobuf:"bytes,12,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	Identity             int32    `protobuf:"varint,13,opt,name=identity,proto3" json:"identity,omitempty"`
	Category             int32    `protobuf:"varint,14,opt,name=category,proto3" json:"category,omitempty"`
	SizeId               int32    `protobuf:"varint,15,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	SecondaryCategory    int32    `protobuf:"varint,16,opt,name=secondary_category,json=secondaryCategory,proto3" json:"secondary_category,omitempty"`
	PageWidth            int32    `protobuf:"varint,20,opt,name=page_width,json=pageWidth,proto3" json:"page_width,omitempty"`
	PageHeight           int32    `protobuf:"varint,17,opt,name=page_height,json=pageHeight,proto3" json:"page_height,omitempty"`
	OtherProperty        string   `protobuf:"bytes,18,opt,name=other_property,json=otherProperty,proto3" json:"other_property,omitempty"`
	SuiteAppType         int32    `protobuf:"varint,21,opt,name=SuiteAppType,proto3" json:"SuiteAppType,omitempty"`
	CreateDevice         string   `protobuf:"bytes,22,opt,name=CreateDevice,proto3" json:"CreateDevice,omitempty"`
	UpdateDevice         string   `protobuf:"bytes,23,opt,name=UpdateDevice,proto3" json:"UpdateDevice,omitempty"`
	CreateSite           int32    `protobuf:"varint,24,opt,name=CreateSite,proto3" json:"CreateSite,omitempty"`
	CreateTime           string   `protobuf:"bytes,25,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,26,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	IsDelete             int32    `protobuf:"varint,27,opt,name=IsDelete,proto3" json:"IsDelete,omitempty"`
	IsBoughtTemplate     int32    `protobuf:"varint,28,opt,name=IsBoughtTemplate,proto3" json:"IsBoughtTemplate,omitempty"`
	IsUsedLocalFonts     int32    `protobuf:"varint,29,opt,name=IsUsedLocalFonts,proto3" json:"IsUsedLocalFonts,omitempty"`
	Status               int32    `protobuf:"varint,30,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorksBracket) Reset()         { *m = WorksBracket{} }
func (m *WorksBracket) String() string { return proto.CompactTextString(m) }
func (*WorksBracket) ProtoMessage()    {}
func (*WorksBracket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{6}
}

func (m *WorksBracket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorksBracket.Unmarshal(m, b)
}
func (m *WorksBracket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorksBracket.Marshal(b, m, deterministic)
}
func (m *WorksBracket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorksBracket.Merge(m, src)
}
func (m *WorksBracket) XXX_Size() int {
	return xxx_messageInfo_WorksBracket.Size(m)
}
func (m *WorksBracket) XXX_DiscardUnknown() {
	xxx_messageInfo_WorksBracket.DiscardUnknown(m)
}

var xxx_messageInfo_WorksBracket proto.InternalMessageInfo

func (m *WorksBracket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WorksBracket) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *WorksBracket) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *WorksBracket) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *WorksBracket) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *WorksBracket) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *WorksBracket) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

func (m *WorksBracket) GetFirstImg() string {
	if m != nil {
		return m.FirstImg
	}
	return ""
}

func (m *WorksBracket) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *WorksBracket) GetEditorVersion() string {
	if m != nil {
		return m.EditorVersion
	}
	return ""
}

func (m *WorksBracket) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *WorksBracket) GetParentEventId() string {
	if m != nil {
		return m.ParentEventId
	}
	return ""
}

func (m *WorksBracket) GetIdentity() int32 {
	if m != nil {
		return m.Identity
	}
	return 0
}

func (m *WorksBracket) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *WorksBracket) GetSizeId() int32 {
	if m != nil {
		return m.SizeId
	}
	return 0
}

func (m *WorksBracket) GetSecondaryCategory() int32 {
	if m != nil {
		return m.SecondaryCategory
	}
	return 0
}

func (m *WorksBracket) GetPageWidth() int32 {
	if m != nil {
		return m.PageWidth
	}
	return 0
}

func (m *WorksBracket) GetPageHeight() int32 {
	if m != nil {
		return m.PageHeight
	}
	return 0
}

func (m *WorksBracket) GetOtherProperty() string {
	if m != nil {
		return m.OtherProperty
	}
	return ""
}

func (m *WorksBracket) GetSuiteAppType() int32 {
	if m != nil {
		return m.SuiteAppType
	}
	return 0
}

func (m *WorksBracket) GetCreateDevice() string {
	if m != nil {
		return m.CreateDevice
	}
	return ""
}

func (m *WorksBracket) GetUpdateDevice() string {
	if m != nil {
		return m.UpdateDevice
	}
	return ""
}

func (m *WorksBracket) GetCreateSite() int32 {
	if m != nil {
		return m.CreateSite
	}
	return 0
}

func (m *WorksBracket) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *WorksBracket) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *WorksBracket) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *WorksBracket) GetIsBoughtTemplate() int32 {
	if m != nil {
		return m.IsBoughtTemplate
	}
	return 0
}

func (m *WorksBracket) GetIsUsedLocalFonts() int32 {
	if m != nil {
		return m.IsUsedLocalFonts
	}
	return 0
}

func (m *WorksBracket) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type DailyPvUvBracket struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	AccessDate           string   `protobuf:"bytes,3,opt,name=access_date,json=accessDate,proto3" json:"access_date,omitempty"`
	EventId              string   `protobuf:"bytes,13,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Pv                   int32    `protobuf:"varint,4,opt,name=pv,proto3" json:"pv,omitempty"`
	Uv                   int32    `protobuf:"varint,5,opt,name=uv,proto3" json:"uv,omitempty"`
	TailAd               int32    `protobuf:"varint,6,opt,name=tail_ad,json=tailAd,proto3" json:"tail_ad,omitempty"`
	Share                int32    `protobuf:"varint,7,opt,name=share,proto3" json:"share,omitempty"`
	TotalShare           int32    `protobuf:"varint,8,opt,name=total_share,json=totalShare,proto3" json:"total_share,omitempty"`
	TotalTailAd          int32    `protobuf:"varint,9,opt,name=total_tail_ad,json=totalTailAd,proto3" json:"total_tail_ad,omitempty"`
	TotalPv              int32    `protobuf:"varint,10,opt,name=total_pv,json=totalPv,proto3" json:"total_pv,omitempty"`
	TotalUv              int32    `protobuf:"varint,11,opt,name=total_uv,json=totalUv,proto3" json:"total_uv,omitempty"`
	Uid                  int32    `protobuf:"varint,12,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyPvUvBracket) Reset()         { *m = DailyPvUvBracket{} }
func (m *DailyPvUvBracket) String() string { return proto.CompactTextString(m) }
func (*DailyPvUvBracket) ProtoMessage()    {}
func (*DailyPvUvBracket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{7}
}

func (m *DailyPvUvBracket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyPvUvBracket.Unmarshal(m, b)
}
func (m *DailyPvUvBracket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyPvUvBracket.Marshal(b, m, deterministic)
}
func (m *DailyPvUvBracket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyPvUvBracket.Merge(m, src)
}
func (m *DailyPvUvBracket) XXX_Size() int {
	return xxx_messageInfo_DailyPvUvBracket.Size(m)
}
func (m *DailyPvUvBracket) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyPvUvBracket.DiscardUnknown(m)
}

var xxx_messageInfo_DailyPvUvBracket proto.InternalMessageInfo

func (m *DailyPvUvBracket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DailyPvUvBracket) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *DailyPvUvBracket) GetAccessDate() string {
	if m != nil {
		return m.AccessDate
	}
	return ""
}

func (m *DailyPvUvBracket) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *DailyPvUvBracket) GetPv() int32 {
	if m != nil {
		return m.Pv
	}
	return 0
}

func (m *DailyPvUvBracket) GetUv() int32 {
	if m != nil {
		return m.Uv
	}
	return 0
}

func (m *DailyPvUvBracket) GetTailAd() int32 {
	if m != nil {
		return m.TailAd
	}
	return 0
}

func (m *DailyPvUvBracket) GetShare() int32 {
	if m != nil {
		return m.Share
	}
	return 0
}

func (m *DailyPvUvBracket) GetTotalShare() int32 {
	if m != nil {
		return m.TotalShare
	}
	return 0
}

func (m *DailyPvUvBracket) GetTotalTailAd() int32 {
	if m != nil {
		return m.TotalTailAd
	}
	return 0
}

func (m *DailyPvUvBracket) GetTotalPv() int32 {
	if m != nil {
		return m.TotalPv
	}
	return 0
}

func (m *DailyPvUvBracket) GetTotalUv() int32 {
	if m != nil {
		return m.TotalUv
	}
	return 0
}

func (m *DailyPvUvBracket) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type DailyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	WorksId              string   `protobuf:"bytes,10,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	Status               int32    `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Uids                 []int32  `protobuf:"varint,11,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	WorksIds             []string `protobuf:"bytes,14,rep,name=WorksIds,proto3" json:"WorksIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyRequest) Reset()         { *m = DailyRequest{} }
func (m *DailyRequest) String() string { return proto.CompactTextString(m) }
func (*DailyRequest) ProtoMessage()    {}
func (*DailyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{8}
}

func (m *DailyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyRequest.Unmarshal(m, b)
}
func (m *DailyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyRequest.Marshal(b, m, deterministic)
}
func (m *DailyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyRequest.Merge(m, src)
}
func (m *DailyRequest) XXX_Size() int {
	return xxx_messageInfo_DailyRequest.Size(m)
}
func (m *DailyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DailyRequest proto.InternalMessageInfo

func (m *DailyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DailyRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DailyRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DailyRequest) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *DailyRequest) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *DailyRequest) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *DailyRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DailyRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DailyRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DailyRequest) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *DailyRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DailyRequest) GetUids() []int32 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *DailyRequest) GetWorksIds() []string {
	if m != nil {
		return m.WorksIds
	}
	return nil
}

type DailyResponse struct {
	Data                 *DailyPvUvBracket `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32             `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32             `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DailyResponse) Reset()         { *m = DailyResponse{} }
func (m *DailyResponse) String() string { return proto.CompactTextString(m) }
func (*DailyResponse) ProtoMessage()    {}
func (*DailyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{9}
}

func (m *DailyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyResponse.Unmarshal(m, b)
}
func (m *DailyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyResponse.Marshal(b, m, deterministic)
}
func (m *DailyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyResponse.Merge(m, src)
}
func (m *DailyResponse) XXX_Size() int {
	return xxx_messageInfo_DailyResponse.Size(m)
}
func (m *DailyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DailyResponse proto.InternalMessageInfo

func (m *DailyResponse) GetData() *DailyPvUvBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DailyResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *DailyResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type DailyIndexResponse struct {
	Data                 []*DailyPvUvBracket `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32               `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32               `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DailyIndexResponse) Reset()         { *m = DailyIndexResponse{} }
func (m *DailyIndexResponse) String() string { return proto.CompactTextString(m) }
func (*DailyIndexResponse) ProtoMessage()    {}
func (*DailyIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de297fef73caeca, []int{10}
}

func (m *DailyIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyIndexResponse.Unmarshal(m, b)
}
func (m *DailyIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyIndexResponse.Marshal(b, m, deterministic)
}
func (m *DailyIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyIndexResponse.Merge(m, src)
}
func (m *DailyIndexResponse) XXX_Size() int {
	return xxx_messageInfo_DailyIndexResponse.Size(m)
}
func (m *DailyIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DailyIndexResponse proto.InternalMessageInfo

func (m *DailyIndexResponse) GetData() []*DailyPvUvBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DailyIndexResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *DailyIndexResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "worksAudit.Request")
	proto.RegisterType((*ShowResponse)(nil), "worksAudit.ShowResponse")
	proto.RegisterType((*Response)(nil), "worksAudit.Response")
	proto.RegisterType((*WorksResponse)(nil), "worksAudit.WorksResponse")
	proto.RegisterType((*WorksDetailResponse)(nil), "worksAudit.WorksDetailResponse")
	proto.RegisterType((*AuditBracket)(nil), "worksAudit.AuditBracket")
	proto.RegisterType((*WorksBracket)(nil), "worksAudit.WorksBracket")
	proto.RegisterType((*DailyPvUvBracket)(nil), "worksAudit.DailyPvUvBracket")
	proto.RegisterType((*DailyRequest)(nil), "worksAudit.DailyRequest")
	proto.RegisterType((*DailyResponse)(nil), "worksAudit.DailyResponse")
	proto.RegisterType((*DailyIndexResponse)(nil), "worksAudit.DailyIndexResponse")
}

func init() { proto.RegisterFile("worksAudit.proto", fileDescriptor_2de297fef73caeca) }

var fileDescriptor_2de297fef73caeca = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xaf, 0xff, 0x5c, 0x6c, 0x4f, 0xec, 0xd4, 0xdd, 0x96, 0x76, 0x93, 0xb6, 0x69, 0x74, 0x02,
	0x14, 0x21, 0xa8, 0x50, 0x40, 0x42, 0x42, 0xe2, 0x21, 0x4d, 0x8a, 0xb0, 0x84, 0x50, 0x74, 0x4e,
	0xc8, 0xa3, 0x75, 0xf5, 0x4d, 0xe2, 0x55, 0xed, 0xbb, 0xe3, 0x6e, 0xef, 0x82, 0x83, 0x90, 0x78,
	0xe2, 0x11, 0xbe, 0x18, 0x12, 0xdf, 0x82, 0x2f, 0xc0, 0x17, 0x40, 0x33, 0xbb, 0x77, 0xbe, 0x23,
	0x89, 0x54, 0xa0, 0x79, 0xe3, 0x25, 0xb9, 0xdf, 0x6f, 0xfe, 0xed, 0xce, 0xce, 0xcc, 0xae, 0x61,
	0x78, 0x11, 0x25, 0xaf, 0xd3, 0xfd, 0x2c, 0x50, 0xfa, 0x79, 0x9c, 0x44, 0x3a, 0x12, 0xb0, 0x62,
	0xdc, 0x3f, 0x9a, 0xd0, 0xf1, 0xf0, 0xbb, 0x0c, 0x53, 0x2d, 0x04, 0xb4, 0x43, 0x7f, 0x81, 0xb2,
	0xb1, 0xd3, 0xd8, 0xed, 0x79, 0xfc, 0x4d, 0x9c, 0x5e, 0xc6, 0x28, 0x9b, 0x86, 0xa3, 0x6f, 0xf1,
	0x00, 0x9c, 0xdc, 0x9f, 0x67, 0x28, 0x5b, 0x4c, 0x1a, 0x20, 0x9e, 0xc1, 0xfa, 0x34, 0x41, 0x5f,
	0xe3, 0x44, 0xab, 0x05, 0xca, 0x36, 0xcb, 0xc0, 0x50, 0xc7, 0x6a, 0xc1, 0x0a, 0x59, 0x1c, 0x94,
	0x0a, 0x8e, 0x51, 0x30, 0x14, 0x2b, 0x3c, 0x86, 0x9e, 0x4a, 0x27, 0x01, 0xce, 0x51, 0xa3, 0x5c,
	0xdb, 0x69, 0xec, 0x3a, 0x5e, 0x57, 0xa5, 0x87, 0x8c, 0x69, 0x21, 0xb1, 0x7f, 0x8e, 0xb2, 0xc3,
	0x3c, 0x7f, 0x93, 0x01, 0xfd, 0x9f, 0xa4, 0xea, 0x12, 0x65, 0xd7, 0x18, 0x10, 0x31, 0x56, 0x97,
	0x28, 0x36, 0xa0, 0xa9, 0x02, 0xd9, 0x63, 0xb6, 0xa9, 0x02, 0xb1, 0x09, 0x5d, 0xde, 0xf7, 0x44,
	0x05, 0x12, 0x38, 0x76, 0x87, 0xf1, 0x28, 0x10, 0x0f, 0x61, 0x2d, 0xd5, 0xbe, 0xce, 0x52, 0xd9,
	0x67, 0x75, 0x8b, 0xc4, 0x10, 0x5a, 0x99, 0x0a, 0xe4, 0x3a, 0x93, 0xf4, 0x49, 0x9a, 0x09, 0xfa,
	0x69, 0x14, 0xca, 0x01, 0xbb, 0xb0, 0x48, 0xec, 0xc0, 0x3a, 0xe7, 0x73, 0x6c, 0xdc, 0x6c, 0xec,
	0xb4, 0x76, 0x1d, 0xaf, 0x4a, 0xb9, 0x39, 0xf4, 0xc7, 0xb3, 0xe8, 0xc2, 0xc3, 0x34, 0x8e, 0xc2,
	0x14, 0xc5, 0x87, 0xd0, 0x0e, 0x7c, 0xed, 0x73, 0xc4, 0xf5, 0x3d, 0xf9, 0xbc, 0x72, 0x4a, 0xfc,
	0xf7, 0x45, 0xe2, 0x4f, 0x5f, 0xa3, 0xf6, 0x58, 0x4b, 0xb8, 0xd0, 0xf7, 0xcf, 0xce, 0x70, 0xaa,
	0x31, 0xf0, 0xa2, 0x8b, 0xd4, 0x2e, 0xa9, 0xc6, 0xd1, 0xb1, 0xe8, 0x48, 0xfb, 0x73, 0x5e, 0x9a,
	0xe3, 0x19, 0xe0, 0x26, 0xd0, 0xbd, 0x26, 0x66, 0xeb, 0x56, 0x63, 0x5e, 0xc0, 0xe0, 0x94, 0x5c,
	0xbf, 0x49, 0x60, 0x56, 0x7c, 0x5b, 0x81, 0x7f, 0x84, 0xfb, 0xec, 0xef, 0x10, 0xb5, 0xaf, 0xe6,
	0x6f, 0x92, 0xeb, 0xb7, 0x1a, 0xfe, 0xe7, 0x26, 0xf4, 0xab, 0x89, 0xbc, 0x52, 0x83, 0xb6, 0xa0,
	0x1a, 0xab, 0x82, 0xda, 0x84, 0x2e, 0xe6, 0x18, 0x6a, 0xaa, 0x4a, 0xd3, 0x63, 0x1d, 0xc6, 0xb5,
	0xaa, 0xec, 0xd4, 0xaa, 0xb2, 0x68, 0xc9, 0x56, 0xa5, 0x25, 0x6f, 0xb9, 0xf9, 0x68, 0xbb, 0x4a,
	0xcf, 0xd1, 0x36, 0x8e, 0x01, 0x42, 0x42, 0x67, 0x1a, 0x85, 0x1a, 0x43, 0xcd, 0x39, 0xea, 0x79,
	0x05, 0x74, 0x7f, 0xe9, 0x40, 0xbf, 0x9a, 0x59, 0x9b, 0x88, 0x46, 0x99, 0x08, 0x09, 0x45, 0xf3,
	0x15, 0xbb, 0x2e, 0x7a, 0xd1, 0xa6, 0xa8, 0xb5, 0x4a, 0x51, 0x19, 0xbc, 0x7d, 0x43, 0x70, 0xa7,
	0x16, 0xdc, 0x48, 0x16, 0x0b, 0x92, 0xac, 0x15, 0x12, 0x86, 0xec, 0x69, 0x96, 0x2d, 0x5e, 0x71,
	0x42, 0xc9, 0x13, 0x01, 0xb1, 0x05, 0xdd, 0x33, 0x95, 0xa4, 0x7a, 0xb4, 0x38, 0xe7, 0x21, 0xd2,
	0xf3, 0x4a, 0x4c, 0xbe, 0x72, 0x4c, 0x52, 0x15, 0x85, 0x7c, 0x8a, 0x3d, 0xaf, 0x80, 0xe2, 0x5d,
	0x18, 0x60, 0xa0, 0x74, 0x94, 0x7c, 0x6b, 0xe5, 0x26, 0x35, 0x75, 0x92, 0xd2, 0xae, 0x71, 0x11,
	0xcf, 0x29, 0xf1, 0x76, 0x92, 0xf4, 0x3c, 0x28, 0xa8, 0x51, 0x20, 0xde, 0x87, 0xbb, 0xb1, 0x9f,
	0x50, 0x01, 0x94, 0x65, 0xd0, 0x37, 0x8e, 0x0c, 0xfd, 0xd2, 0x16, 0xc3, 0x16, 0x74, 0x55, 0x80,
	0xa1, 0x56, 0x7a, 0x69, 0x6b, 0xae, 0xc4, 0x24, 0x9b, 0xfa, 0x1a, 0xcf, 0xa3, 0x64, 0x29, 0x37,
	0x8c, 0xac, 0xc0, 0xe2, 0x11, 0x74, 0x68, 0x3a, 0x92, 0xdf, 0xbb, 0xb6, 0x8a, 0xd4, 0x25, 0x05,
	0xfe, 0x08, 0x44, 0x8a, 0xd3, 0x28, 0x0c, 0xfc, 0x64, 0x39, 0x29, 0xcd, 0x87, 0xac, 0x73, 0xaf,
	0x94, 0x1c, 0x14, 0x7e, 0x9e, 0x02, 0xf0, 0xa8, 0xbd, 0x50, 0x81, 0x9e, 0xc9, 0x07, 0xac, 0xc6,
	0xc3, 0xf7, 0x94, 0x08, 0xda, 0x27, 0x8b, 0x67, 0xa8, 0xce, 0x67, 0x5a, 0xde, 0x63, 0x39, 0x5b,
	0x7c, 0xc5, 0x8c, 0x78, 0x0f, 0x36, 0x22, 0x3d, 0xc3, 0x64, 0x12, 0x27, 0x51, 0x8c, 0x89, 0x5e,
	0x4a, 0x61, 0xb6, 0xc9, 0xec, 0x91, 0x25, 0xa9, 0xf7, 0xc6, 0x99, 0xd2, 0xb8, 0x1f, 0xc7, 0xc7,
	0x54, 0xe3, 0xef, 0x98, 0xde, 0xab, 0x72, 0xa4, 0x73, 0xc0, 0x85, 0x7d, 0x88, 0xb9, 0x9a, 0xa2,
	0x7c, 0xc8, 0x8e, 0x6a, 0x1c, 0xe9, 0x9c, 0x70, 0x6d, 0x5b, 0x9d, 0x47, 0x46, 0xa7, 0xca, 0x89,
	0x6d, 0x00, 0x63, 0x33, 0x56, 0x1a, 0xa5, 0x34, 0x4b, 0x5e, 0x31, 0x2b, 0x39, 0xf5, 0x87, 0xdc,
	0x34, 0x47, 0xb7, 0x62, 0x48, 0x7e, 0x52, 0xf6, 0x8f, 0xdc, 0x32, 0xf2, 0x15, 0x43, 0xc7, 0x32,
	0xb2, 0x0d, 0x24, 0x1f, 0x9b, 0x63, 0x29, 0xb0, 0xf8, 0x00, 0x86, 0xa3, 0xf4, 0x45, 0x94, 0x9d,
	0xcf, 0xf4, 0xb1, 0x2d, 0x06, 0xf9, 0x84, 0x75, 0xae, 0xf0, 0x46, 0xf7, 0x24, 0xc5, 0xe0, 0xeb,
	0x68, 0xea, 0xcf, 0xbf, 0x8c, 0x42, 0x9d, 0xca, 0xa7, 0x85, 0x6e, 0x9d, 0xa7, 0x99, 0x61, 0xaf,
	0xa0, 0x6d, 0x73, 0xda, 0xf6, 0xf6, 0xf9, 0xad, 0x09, 0xc3, 0x43, 0x5f, 0xcd, 0x97, 0x47, 0xf9,
	0x49, 0x7e, 0x53, 0x53, 0x0e, 0xa1, 0x15, 0x97, 0x63, 0x88, 0x3e, 0xe9, 0x58, 0xfd, 0xe9, 0x14,
	0xd3, 0x74, 0x42, 0xbb, 0xb2, 0x13, 0x07, 0x0c, 0x75, 0x48, 0x6b, 0xab, 0x8e, 0xaf, 0x41, 0x7d,
	0x7c, 0x6d, 0x40, 0x33, 0xce, 0xb9, 0x67, 0x1d, 0xaf, 0x19, 0xe7, 0x84, 0xb3, 0x9c, 0x7b, 0xd5,
	0xf1, 0x9a, 0x59, 0x4e, 0x95, 0x49, 0x43, 0x7a, 0xe2, 0x07, 0x76, 0xdc, 0xac, 0x11, 0xdc, 0xe7,
	0x7e, 0x4f, 0x67, 0x7e, 0x52, 0x5c, 0xf5, 0x06, 0x70, 0x27, 0xd1, 0x90, 0x9d, 0x18, 0x99, 0xb9,
	0xed, 0x81, 0xa9, 0x31, 0x2b, 0xb8, 0x30, 0x30, 0x0a, 0x85, 0x57, 0x33, 0x76, 0x8d, 0xd5, 0xb1,
	0x71, 0xbd, 0x09, 0x5d, 0xa3, 0x13, 0xe7, 0xdc, 0xaf, 0x8e, 0xd7, 0x61, 0x7c, 0x94, 0xaf, 0x44,
	0x59, 0x6e, 0x27, 0xbe, 0x11, 0x9d, 0xe4, 0xc5, 0x48, 0xea, 0x97, 0x23, 0xc9, 0xfd, 0xbd, 0x09,
	0x7d, 0x4e, 0xe7, 0xff, 0x4f, 0xa7, 0x1b, 0x9e, 0x4e, 0x02, 0xda, 0x99, 0x0a, 0xe8, 0xf2, 0xa4,
	0x97, 0x10, 0x7f, 0x53, 0x43, 0x9c, 0x1a, 0x33, 0xf3, 0x42, 0xea, 0x79, 0x25, 0x76, 0x7f, 0x80,
	0x81, 0x4d, 0xa8, 0xbd, 0xb3, 0x3f, 0xae, 0xdd, 0xd9, 0x4f, 0xaa, 0x77, 0xf6, 0xdf, 0x0b, 0xf9,
	0x3f, 0xdf, 0xdb, 0x3f, 0x35, 0x40, 0xb0, 0xd3, 0x51, 0x18, 0xe0, 0xf7, 0xd7, 0x2c, 0xa1, 0x75,
	0xdb, 0x4b, 0xd8, 0xfb, 0xb3, 0x01, 0x70, 0x5a, 0xfa, 0x17, 0x9f, 0x41, 0x9b, 0x5e, 0x8b, 0xe2,
	0x7e, 0x35, 0xa8, 0x2d, 0xb6, 0xad, 0xda, 0x03, 0xa6, 0xfa, 0xa8, 0x74, 0xef, 0x88, 0x4f, 0xc1,
	0xe1, 0x4d, 0x5c, 0x6f, 0xf9, 0xa0, 0x4e, 0x96, 0x56, 0x9f, 0xc3, 0x3a, 0x07, 0x37, 0xd3, 0xeb,
	0x1f, 0xdb, 0x32, 0xf7, 0x2f, 0x6c, 0xf7, 0xbe, 0x01, 0x87, 0xe3, 0x8a, 0x97, 0x76, 0x01, 0xe6,
	0xe1, 0x76, 0xbd, 0x93, 0x67, 0x57, 0xde, 0x6d, 0xf5, 0x67, 0x9e, 0x7b, 0x67, 0xef, 0xd7, 0x06,
	0xf4, 0xca, 0xa3, 0x11, 0x5f, 0xd8, 0x24, 0xca, 0x2b, 0x27, 0x57, 0xb8, 0xdc, 0xbc, 0x46, 0x52,
	0x6e, 0xec, 0xa0, 0x48, 0xe5, 0xcd, 0xf6, 0xdb, 0x57, 0x24, 0xb5, 0x0a, 0x72, 0xef, 0xbc, 0x5a,
	0xe3, 0x9f, 0x5c, 0x9f, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xd9, 0x37, 0x94, 0x86, 0x0d,
	0x00, 0x00,
}
