// Code generated by protoc-gen-go. DO NOT EDIT.
// source: font.proto

package font

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Id                   int32    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Ids                  []*Ids   `protobuf:"bytes,5,rep,name=Ids,json=ids,proto3" json:"Ids,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fe186f2a10d1c7c, []int{0}
}

func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (m *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(m, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

func (m *IndexRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *IndexRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *IndexRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IndexRequest) GetIds() []*Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *IndexRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Ids struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fe186f2a10d1c7c, []int{1}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type IndexResponse struct {
	Data                 []*Font  `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32    `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32    `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fe186f2a10d1c7c, []int{2}
}

func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (m *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(m, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

func (m *IndexResponse) GetData() []*Font {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IndexResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *IndexResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Font struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Style                string   `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Link                 string   `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	PersonPrice          int32    `protobuf:"varint,6,opt,name=personPrice,proto3" json:"personPrice,omitempty"`
	EnterPrisePrice      int32    `protobuf:"varint,7,opt,name=enterPrisePrice,proto3" json:"enterPrisePrice,omitempty"`
	EnableLease          int32    `protobuf:"varint,8,opt,name=enableLease,proto3" json:"enableLease,omitempty"`
	FontIdNo             string   `protobuf:"bytes,9,opt,name=fontIdNo,proto3" json:"fontIdNo,omitempty"`
	PreviewTextUrl       string   `protobuf:"bytes,10,opt,name=previewTextUrl,proto3" json:"previewTextUrl,omitempty"`
	PreviewImg           string   `protobuf:"bytes,11,opt,name=previewImg,proto3" json:"previewImg,omitempty"`
	OrderPreviewImg      string   `protobuf:"bytes,12,opt,name=orderPreviewImg,proto3" json:"orderPreviewImg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Font) Reset()         { *m = Font{} }
func (m *Font) String() string { return proto.CompactTextString(m) }
func (*Font) ProtoMessage()    {}
func (*Font) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fe186f2a10d1c7c, []int{3}
}

func (m *Font) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Font.Unmarshal(m, b)
}
func (m *Font) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Font.Marshal(b, m, deterministic)
}
func (m *Font) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Font.Merge(m, src)
}
func (m *Font) XXX_Size() int {
	return xxx_messageInfo_Font.Size(m)
}
func (m *Font) XXX_DiscardUnknown() {
	xxx_messageInfo_Font.DiscardUnknown(m)
}

var xxx_messageInfo_Font proto.InternalMessageInfo

func (m *Font) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Font) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *Font) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Font) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Font) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Font) GetPersonPrice() int32 {
	if m != nil {
		return m.PersonPrice
	}
	return 0
}

func (m *Font) GetEnterPrisePrice() int32 {
	if m != nil {
		return m.EnterPrisePrice
	}
	return 0
}

func (m *Font) GetEnableLease() int32 {
	if m != nil {
		return m.EnableLease
	}
	return 0
}

func (m *Font) GetFontIdNo() string {
	if m != nil {
		return m.FontIdNo
	}
	return ""
}

func (m *Font) GetPreviewTextUrl() string {
	if m != nil {
		return m.PreviewTextUrl
	}
	return ""
}

func (m *Font) GetPreviewImg() string {
	if m != nil {
		return m.PreviewImg
	}
	return ""
}

func (m *Font) GetOrderPreviewImg() string {
	if m != nil {
		return m.OrderPreviewImg
	}
	return ""
}

func init() {
	proto.RegisterType((*IndexRequest)(nil), "font.IndexRequest")
	proto.RegisterType((*Ids)(nil), "font.Ids")
	proto.RegisterType((*IndexResponse)(nil), "font.IndexResponse")
	proto.RegisterType((*Font)(nil), "font.Font")
}

func init() { proto.RegisterFile("font.proto", fileDescriptor_0fe186f2a10d1c7c) }

var fileDescriptor_0fe186f2a10d1c7c = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x49, 0x76, 0x37, 0x74, 0x27, 0x69, 0x41, 0xc3, 0x1f, 0x59, 0x45, 0xaa, 0xa2, 0x3d,
	0xa0, 0x9c, 0x7a, 0x08, 0x47, 0xee, 0x48, 0x2b, 0x21, 0x54, 0x19, 0x78, 0x00, 0x37, 0x9e, 0x54,
	0x16, 0x5b, 0x7b, 0xb1, 0x1d, 0x5a, 0xb8, 0xf2, 0xb6, 0x3c, 0x05, 0xf2, 0x78, 0xbb, 0xda, 0xe4,
	0x94, 0x99, 0x5f, 0x3e, 0x7f, 0x3b, 0xfe, 0x3c, 0x00, 0x7b, 0x67, 0xe3, 0x75, 0xef, 0x5d, 0x74,
	0x58, 0xa6, 0xba, 0xf9, 0x3b, 0x83, 0x55, 0x6b, 0x35, 0x3d, 0x4a, 0xfa, 0x79, 0xa0, 0x10, 0x11,
	0xa1, 0xec, 0xd5, 0x1d, 0x89, 0xd9, 0x7a, 0xb6, 0xa9, 0x24, 0xd7, 0x78, 0x09, 0x67, 0xe9, 0xf7,
	0xab, 0xf9, 0x43, 0x62, 0xce, 0x7c, 0xec, 0xf1, 0x02, 0xe6, 0x46, 0x8b, 0x92, 0xe9, 0xdc, 0x68,
	0x7c, 0x07, 0x45, 0xab, 0x83, 0xa8, 0xd6, 0xc5, 0x66, 0xb9, 0xad, 0xaf, 0xf9, 0x83, 0xad, 0x0e,
	0xb2, 0x30, 0x3a, 0xe0, 0x5b, 0x58, 0x84, 0xa8, 0xe2, 0x21, 0x88, 0x05, 0x1f, 0x18, 0xba, 0xe6,
	0x0d, 0x1f, 0x1a, 0xbc, 0x66, 0x4f, 0x5e, 0x8d, 0x81, 0xf3, 0x61, 0xb6, 0xd0, 0x3b, 0x1b, 0x08,
	0xaf, 0xa0, 0xd4, 0x2a, 0x2a, 0xb1, 0x62, 0x77, 0xc8, 0xee, 0x9f, 0x9c, 0x8d, 0x92, 0x39, 0x36,
	0xb0, 0x52, 0xfb, 0x3d, 0xed, 0x22, 0x69, 0xe9, 0x1e, 0x82, 0x58, 0xb2, 0xd5, 0x11, 0xc3, 0xd7,
	0x50, 0x45, 0x17, 0x55, 0x27, 0xce, 0xf9, 0xcf, 0xdc, 0x34, 0xff, 0xe6, 0x50, 0x26, 0x23, 0x7c,
	0x09, 0xc5, 0x61, 0x1c, 0x22, 0x95, 0xe9, 0x40, 0x88, 0xbf, 0xbb, 0x7c, 0xf5, 0x5a, 0xe6, 0x26,
	0xe5, 0x64, 0xd5, 0x3d, 0x89, 0x82, 0x21, 0xd7, 0x7c, 0x3d, 0x77, 0xf0, 0x3b, 0xe2, 0x3c, 0x6a,
	0x39, 0x74, 0x49, 0xdb, 0x19, 0xfb, 0x43, 0x54, 0x59, 0x9b, 0x6a, 0x5c, 0xc3, 0xb2, 0x27, 0x1f,
	0x9c, 0xbd, 0xf1, 0x66, 0x47, 0x43, 0x1e, 0x53, 0x84, 0x1b, 0x78, 0x41, 0x36, 0x92, 0xbf, 0xf1,
	0x26, 0x50, 0x56, 0x3d, 0x67, 0xd5, 0x29, 0x4e, 0x5e, 0x64, 0xd5, 0x6d, 0x47, 0x9f, 0x49, 0x05,
	0x12, 0x67, 0xd9, 0x6b, 0x82, 0xd2, 0x0b, 0xa6, 0xac, 0x5a, 0xfd, 0xc5, 0x89, 0x9a, 0xa7, 0x18,
	0x7b, 0x7c, 0x0f, 0x17, 0xbd, 0xa7, 0x5f, 0x86, 0x1e, 0xbe, 0xd1, 0x63, 0xfc, 0xee, 0x3b, 0x01,
	0xac, 0x38, 0xa1, 0x78, 0x05, 0x30, 0x90, 0xf6, 0xfe, 0x8e, 0xa3, 0xad, 0xe5, 0x84, 0xa4, 0x79,
	0x9d, 0xd7, 0x69, 0xb0, 0x51, 0xb4, 0x62, 0xd1, 0x29, 0xde, 0x7e, 0x84, 0x2a, 0x65, 0x1d, 0x70,
	0x0b, 0x15, 0x3f, 0x30, 0xe2, 0xb0, 0x28, 0x93, 0x4d, 0xbc, 0x7c, 0x75, 0xc4, 0xf2, 0x06, 0x34,
	0xcf, 0x6e, 0x17, 0xbc, 0xbe, 0x1f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xa7, 0xa3, 0x17,
	0xcc, 0x02, 0x00, 0x00,
}
