// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auditConf.proto

package auditConf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_703ab07fe430db0d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

type Response struct {
	Data                 []*Response_Notify `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_703ab07fe430db0d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []*Response_Notify {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response_Notify struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Notify) Reset()         { *m = Response_Notify{} }
func (m *Response_Notify) String() string { return proto.CompactTextString(m) }
func (*Response_Notify) ProtoMessage()    {}
func (*Response_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_703ab07fe430db0d, []int{1, 0}
}

func (m *Response_Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Notify.Unmarshal(m, b)
}
func (m *Response_Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Notify.Marshal(b, m, deterministic)
}
func (m *Response_Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Notify.Merge(m, src)
}
func (m *Response_Notify) XXX_Size() int {
	return xxx_messageInfo_Response_Notify.Size(m)
}
func (m *Response_Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Notify proto.InternalMessageInfo

func (m *Response_Notify) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response_Notify) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_Notify) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Response_Notify) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response_Notify) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Response_Notify) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Response_Notify) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_Notify)(nil), "Response.Notify")
}

func init() { proto.RegisterFile("auditConf.proto", fileDescriptor_703ab07fe430db0d) }

var fileDescriptor_703ab07fe430db0d = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x9a, 0x84, 0xe4, 0x8a, 0x00, 0x59, 0x0c, 0x56, 0x11, 0x34, 0x8a, 0x18, 0x32,
	0x65, 0x28, 0x4f, 0x80, 0xca, 0xc2, 0xc2, 0x10, 0x60, 0xae, 0x0c, 0xbe, 0x0a, 0x4b, 0x4d, 0x1c,
	0x6a, 0x07, 0xe8, 0x3b, 0xf0, 0x3a, 0xf0, 0x4c, 0x3c, 0x06, 0xca, 0x99, 0x76, 0xcb, 0x03, 0x74,
	0xbb, 0xfb, 0xfe, 0x4f, 0x27, 0x9f, 0xce, 0x70, 0x22, 0x3b, 0xa5, 0xdd, 0xdc, 0x34, 0xcb, 0xb2,
	0x5d, 0x1b, 0x67, 0xf2, 0x1f, 0x06, 0x87, 0x15, 0xbe, 0x75, 0x68, 0x1d, 0x3f, 0x86, 0x40, 0x2b,
	0x91, 0x66, 0xac, 0x88, 0xaa, 0x40, 0x2b, 0xce, 0x21, 0x6c, 0x64, 0x8d, 0x82, 0x65, 0xac, 0x48,
	0x2b, 0xaa, 0x7b, 0xe6, 0x36, 0x2d, 0x8a, 0xc0, 0xb3, 0xbe, 0xe6, 0x67, 0x10, 0xbd, 0xcb, 0x55,
	0x87, 0x62, 0x44, 0xd0, 0x37, 0x7c, 0x0a, 0xe3, 0x97, 0x35, 0x4a, 0x87, 0x0b, 0xa7, 0x6b, 0x14,
	0x21, 0x65, 0xe0, 0xd1, 0xa3, 0xae, 0x49, 0xe8, 0x5a, 0xb5, 0x13, 0x22, 0x2f, 0x78, 0x44, 0xc2,
	0x39, 0xa4, 0xda, 0x2e, 0x14, 0xae, 0xd0, 0xa1, 0x88, 0xe9, 0x59, 0x89, 0xb6, 0xb7, 0xd4, 0xe7,
	0xbf, 0x0c, 0x92, 0x0a, 0x6d, 0x6b, 0x1a, 0x8b, 0xfc, 0x0a, 0x42, 0x25, 0x9d, 0x14, 0x47, 0xd9,
	0xa8, 0x18, 0xcf, 0x4e, 0xcb, 0x6d, 0x50, 0xde, 0x1b, 0xa7, 0x97, 0x9b, 0x8a, 0xd2, 0xc9, 0x37,
	0x83, 0xd8, 0x83, 0xbd, 0x5a, 0x75, 0xf6, 0xc5, 0x20, 0xbd, 0xd9, 0xde, 0x8d, 0x4f, 0x21, 0x9e,
	0xd3, 0x64, 0x9e, 0x94, 0xff, 0x97, 0x9b, 0xa4, 0xbb, 0x8d, 0xf3, 0x83, 0x5e, 0x78, 0xa2, 0xc9,
	0x43, 0xc2, 0x05, 0x84, 0x0f, 0xaf, 0xe6, 0x63, 0x28, 0xbe, 0x84, 0xe8, 0xae, 0x51, 0xf8, 0x39,
	0x90, 0x3f, 0xc7, 0xf4, 0x73, 0xae, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x08, 0xc6, 0x7c,
	0x4c, 0x02, 0x00, 0x00,
}
