// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auditConf.proto

package auditConf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Limit                int32    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_703ab07fe430db0d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Request) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Request) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AuditConfBracket struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditConfBracket) Reset()         { *m = AuditConfBracket{} }
func (m *AuditConfBracket) String() string { return proto.CompactTextString(m) }
func (*AuditConfBracket) ProtoMessage()    {}
func (*AuditConfBracket) Descriptor() ([]byte, []int) {
	return fileDescriptor_703ab07fe430db0d, []int{1}
}

func (m *AuditConfBracket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditConfBracket.Unmarshal(m, b)
}
func (m *AuditConfBracket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditConfBracket.Marshal(b, m, deterministic)
}
func (m *AuditConfBracket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditConfBracket.Merge(m, src)
}
func (m *AuditConfBracket) XXX_Size() int {
	return xxx_messageInfo_AuditConfBracket.Size(m)
}
func (m *AuditConfBracket) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditConfBracket.DiscardUnknown(m)
}

var xxx_messageInfo_AuditConfBracket proto.InternalMessageInfo

func (m *AuditConfBracket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuditConfBracket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuditConfBracket) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuditConfBracket) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AuditConfBracket) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AuditConfBracket) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *AuditConfBracket) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

type Response struct {
	Data                 []*AuditConfBracket `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32               `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32               `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_703ab07fe430db0d, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []*AuditConfBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *Response) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*AuditConfBracket)(nil), "AuditConfBracket")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("auditConf.proto", fileDescriptor_703ab07fe430db0d) }

var fileDescriptor_703ab07fe430db0d = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x9b, 0xa4, 0xc9, 0xb4, 0xfc, 0x59, 0x08, 0x59, 0x20, 0x68, 0x15, 0x09, 0xa9,
	0xab, 0x2c, 0xca, 0x09, 0xa0, 0x6c, 0xd8, 0x06, 0x58, 0x57, 0xa6, 0x9e, 0x08, 0xab, 0x49, 0x1c,
	0x6a, 0x87, 0xc2, 0x1d, 0xb8, 0x13, 0x97, 0xe1, 0x20, 0x28, 0xe3, 0xb6, 0x12, 0x48, 0x3d, 0x00,
	0x3b, 0xbf, 0xef, 0x3d, 0x4d, 0xe6, 0x45, 0x03, 0x87, 0xa2, 0x91, 0xca, 0x4e, 0x75, 0x95, 0xa7,
	0xf5, 0x52, 0x5b, 0x9d, 0x7c, 0x7b, 0xd0, 0xcb, 0xf0, 0xb5, 0x41, 0x63, 0xd9, 0x01, 0x74, 0x94,
	0xe4, 0xf1, 0xc8, 0x1b, 0x07, 0x59, 0x47, 0x49, 0xc6, 0xc0, 0xaf, 0x44, 0x89, 0xdc, 0x1b, 0x79,
	0xe3, 0x38, 0xa3, 0x77, 0xcb, 0xec, 0x47, 0x8d, 0xbc, 0xe3, 0x58, 0xfb, 0x66, 0x27, 0x10, 0xbc,
	0x89, 0xa2, 0x41, 0xde, 0x25, 0xe8, 0x04, 0x1b, 0x42, 0x7f, 0xbe, 0x44, 0x61, 0x71, 0x66, 0x55,
	0x89, 0xdc, 0x27, 0x0f, 0x1c, 0x7a, 0x54, 0x25, 0x05, 0x9a, 0x5a, 0x6e, 0x03, 0x81, 0x0b, 0x38,
	0x44, 0x81, 0x73, 0x88, 0x95, 0x99, 0x49, 0x2c, 0xd0, 0x22, 0x0f, 0x69, 0xad, 0x48, 0x99, 0x3b,
	0xd2, 0xed, 0x47, 0x0b, 0x55, 0x2a, 0xcb, 0x7b, 0x64, 0x38, 0xc1, 0x4e, 0x21, 0xd4, 0x79, 0x6e,
	0xd0, 0xf2, 0x88, 0xf0, 0x5a, 0x25, 0x5f, 0x1e, 0x1c, 0xdd, 0x6c, 0xaa, 0xdf, 0x2e, 0xc5, 0x7c,
	0x81, 0xff, 0xab, 0x6f, 0xb2, 0x80, 0x28, 0x43, 0x53, 0xeb, 0xca, 0x20, 0xbb, 0x02, 0x5f, 0x0a,
	0x2b, 0xf8, 0x60, 0xd4, 0x1d, 0xf7, 0x27, 0xc7, 0xe9, 0xdf, 0x66, 0x19, 0xd9, 0x2c, 0x81, 0x81,
	0xc8, 0x73, 0x9c, 0x5b, 0x94, 0x99, 0x5e, 0x19, 0xde, 0xa7, 0x91, 0xbf, 0x58, 0xdb, 0xc5, 0x6a,
	0x2b, 0x0a, 0xbe, 0xef, 0x7e, 0x23, 0x89, 0xc9, 0xa7, 0x07, 0xf1, 0x76, 0x28, 0x1b, 0x42, 0x38,
	0xa5, 0x1a, 0x2c, 0x4a, 0xd7, 0xb7, 0x72, 0x16, 0xa7, 0x9b, 0x6d, 0x92, 0xbd, 0x36, 0xf0, 0x44,
	0x35, 0x76, 0x05, 0x2e, 0xc0, 0x7f, 0x78, 0xd1, 0xab, 0x5d, 0xf6, 0x25, 0x04, 0xf7, 0x95, 0xc4,
	0xf7, 0x1d, 0xfe, 0x73, 0x48, 0xb7, 0x7a, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xa4, 0xf9,
	0x9b, 0xbe, 0x02, 0x00, 0x00,
}
