// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auditLog.proto

package AuditLog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,11,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Limit                int32    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	Reason               string   `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	WorksId              string   `protobuf:"bytes,14,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	Ids                  []int32  `protobuf:"varint,10,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_05adb379ee134fa1, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Request) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Request) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Request) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *Request) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type AuditLogBracket struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	WorksId              string   `protobuf:"bytes,3,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditLogBracket) Reset()         { *m = AuditLogBracket{} }
func (m *AuditLogBracket) String() string { return proto.CompactTextString(m) }
func (*AuditLogBracket) ProtoMessage()    {}
func (*AuditLogBracket) Descriptor() ([]byte, []int) {
	return fileDescriptor_05adb379ee134fa1, []int{1}
}

func (m *AuditLogBracket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogBracket.Unmarshal(m, b)
}
func (m *AuditLogBracket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogBracket.Marshal(b, m, deterministic)
}
func (m *AuditLogBracket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogBracket.Merge(m, src)
}
func (m *AuditLogBracket) XXX_Size() int {
	return xxx_messageInfo_AuditLogBracket.Size(m)
}
func (m *AuditLogBracket) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogBracket.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogBracket proto.InternalMessageInfo

func (m *AuditLogBracket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuditLogBracket) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuditLogBracket) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *AuditLogBracket) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *AuditLogBracket) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuditLogBracket) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type LogShowResponse struct {
	Data                 *AuditLogBracket `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32            `protobuf:"varint,2,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32            `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogShowResponse) Reset()         { *m = LogShowResponse{} }
func (m *LogShowResponse) String() string { return proto.CompactTextString(m) }
func (*LogShowResponse) ProtoMessage()    {}
func (*LogShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05adb379ee134fa1, []int{2}
}

func (m *LogShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogShowResponse.Unmarshal(m, b)
}
func (m *LogShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogShowResponse.Marshal(b, m, deterministic)
}
func (m *LogShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogShowResponse.Merge(m, src)
}
func (m *LogShowResponse) XXX_Size() int {
	return xxx_messageInfo_LogShowResponse.Size(m)
}
func (m *LogShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogShowResponse proto.InternalMessageInfo

func (m *LogShowResponse) GetData() *AuditLogBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LogShowResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *LogShowResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AuditLogResponse struct {
	Data                 []*AuditLogBracket `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32              `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32              `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AuditLogResponse) Reset()         { *m = AuditLogResponse{} }
func (m *AuditLogResponse) String() string { return proto.CompactTextString(m) }
func (*AuditLogResponse) ProtoMessage()    {}
func (*AuditLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05adb379ee134fa1, []int{3}
}

func (m *AuditLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogResponse.Unmarshal(m, b)
}
func (m *AuditLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogResponse.Marshal(b, m, deterministic)
}
func (m *AuditLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogResponse.Merge(m, src)
}
func (m *AuditLogResponse) XXX_Size() int {
	return xxx_messageInfo_AuditLogResponse.Size(m)
}
func (m *AuditLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogResponse proto.InternalMessageInfo

func (m *AuditLogResponse) GetData() []*AuditLogBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuditLogResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *AuditLogResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "AuditLog.Request")
	proto.RegisterType((*AuditLogBracket)(nil), "AuditLog.AuditLogBracket")
	proto.RegisterType((*LogShowResponse)(nil), "AuditLog.LogShowResponse")
	proto.RegisterType((*AuditLogResponse)(nil), "AuditLog.AuditLogResponse")
}

func init() { proto.RegisterFile("auditLog.proto", fileDescriptor_05adb379ee134fa1) }

var fileDescriptor_05adb379ee134fa1 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcb, 0x72, 0xd3, 0x30,
	0x14, 0xad, 0xed, 0x38, 0x8f, 0x9b, 0x47, 0x8b, 0x86, 0x61, 0xd4, 0xb2, 0x20, 0xe3, 0x55, 0x37,
	0x64, 0x51, 0xf6, 0x0c, 0x30, 0x6c, 0x3a, 0xd3, 0x95, 0x61, 0x9f, 0x11, 0xd1, 0x4d, 0xd1, 0x34,
	0xb6, 0x8c, 0x25, 0x13, 0x1e, 0xbf, 0xc0, 0x1f, 0xf0, 0x59, 0xfc, 0x10, 0xa3, 0x2b, 0xab, 0x71,
	0x5c, 0x86, 0x45, 0x77, 0xf7, 0x1c, 0x9d, 0xe8, 0x9c, 0x7b, 0x62, 0xc1, 0x42, 0x34, 0x52, 0xd9,
	0x1b, 0x7d, 0xbb, 0xaa, 0x6a, 0x6d, 0x35, 0x1b, 0xbf, 0x6d, 0x71, 0xf6, 0x27, 0x86, 0x51, 0x8e,
	0x5f, 0x1a, 0x34, 0x96, 0x2d, 0x20, 0x56, 0x92, 0x4f, 0x96, 0xd1, 0x65, 0x9a, 0xc7, 0x4a, 0xb2,
	0x33, 0x48, 0x1a, 0x25, 0xf9, 0x94, 0x08, 0x37, 0x32, 0x06, 0x83, 0x52, 0x14, 0xc8, 0xa3, 0x65,
	0x74, 0x39, 0xc9, 0x69, 0x76, 0x9c, 0xfd, 0x5e, 0x21, 0x8f, 0x3d, 0xe7, 0x66, 0xf6, 0x14, 0xd2,
	0xaf, 0x62, 0xd7, 0x20, 0x4f, 0x88, 0xf4, 0x80, 0xbd, 0x80, 0xe9, 0xa6, 0x46, 0x61, 0x71, 0x6d,
	0x55, 0x81, 0x7c, 0x40, 0x67, 0xe0, 0xa9, 0x8f, 0xaa, 0x20, 0x41, 0x53, 0xc9, 0x7b, 0x41, 0xea,
	0x05, 0x9e, 0x22, 0xc1, 0x73, 0x98, 0x28, 0xb3, 0x96, 0xb8, 0x43, 0x8b, 0x7c, 0x48, 0xb9, 0xc6,
	0xca, 0xbc, 0x27, 0xec, 0x4c, 0x77, 0xaa, 0x50, 0x96, 0x8f, 0xe8, 0xc0, 0x03, 0xf6, 0x0c, 0x86,
	0x7a, 0xbb, 0x35, 0x68, 0xf9, 0x98, 0xe8, 0x16, 0x39, 0xbe, 0x46, 0x61, 0x74, 0xc9, 0x67, 0x64,
	0xd3, 0x22, 0xc7, 0x1b, 0x2b, 0x6c, 0x63, 0xf8, 0xdc, 0xeb, 0x3d, 0x62, 0xe7, 0x30, 0xde, 0xeb,
	0xfa, 0xce, 0xac, 0x95, 0xe4, 0x0b, 0xfa, 0xc5, 0x88, 0xf0, 0x35, 0xf5, 0xa4, 0xa4, 0xe1, 0xb0,
	0x4c, 0x5c, 0x4f, 0x4a, 0x9a, 0xec, 0x77, 0x04, 0xa7, 0xa1, 0xe2, 0x77, 0xb5, 0xd8, 0xdc, 0x61,
	0x68, 0x37, 0xea, 0xb7, 0x1b, 0x1f, 0xda, 0xed, 0x5a, 0x24, 0xc7, 0x16, 0x87, 0xb4, 0x83, 0xa3,
	0xb4, 0xa1, 0xfc, 0xb4, 0x53, 0x7e, 0xaf, 0xe6, 0x61, 0xbf, 0xe6, 0xec, 0x07, 0x9c, 0xde, 0xe8,
	0xdb, 0x0f, 0x9f, 0xf5, 0x3e, 0x47, 0x53, 0xe9, 0xd2, 0x20, 0x7b, 0x09, 0x03, 0x29, 0xac, 0xa0,
	0x78, 0xd3, 0xab, 0xf3, 0x55, 0x08, 0xbf, 0xea, 0x6d, 0x91, 0x93, 0x8c, 0x65, 0x30, 0x13, 0xdb,
	0x2d, 0x6e, 0x2c, 0xca, 0x5c, 0xef, 0x4d, 0xbb, 0xc4, 0x11, 0xe7, 0xfe, 0x0e, 0xab, 0xad, 0xd8,
	0xd1, 0x2a, 0x69, 0xee, 0x41, 0xf6, 0x13, 0xce, 0xc2, 0x95, 0x0f, 0xcc, 0x67, 0xcb, 0xe4, 0x31,
	0xe6, 0xd3, 0xff, 0x99, 0xcf, 0x3b, 0xe6, 0x57, 0xbf, 0x22, 0xb8, 0xff, 0xf2, 0xd9, 0x1b, 0x98,
	0x87, 0xf9, 0xba, 0x94, 0xf8, 0x8d, 0x3d, 0x39, 0x18, 0xb7, 0x2f, 0xe2, 0xe2, 0xe2, 0x61, 0x96,
	0x90, 0x3a, 0x3b, 0x61, 0xaf, 0x61, 0x16, 0x58, 0x57, 0xe6, 0xbf, 0x2e, 0xe8, 0x2c, 0xd3, 0xab,
	0x3c, 0x3b, 0xf9, 0x34, 0xa4, 0xc7, 0xf8, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0xa7,
	0x5c, 0x58, 0x9e, 0x03, 0x00, 0x00,
}
