// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,11,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Reason               string   `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	WorksId              string   `protobuf:"bytes,14,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	ClosureDay           string   `protobuf:"bytes,15,opt,name=closure_day,json=closureDay,proto3" json:"closure_day,omitempty"`
	Ids                  []int32  `protobuf:"varint,10,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *Request) GetClosureDay() string {
	if m != nil {
		return m.ClosureDay
	}
	return ""
}

func (m *Request) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type UserBracket struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	UserBalance          int32    `protobuf:"varint,4,opt,name=userBalance,proto3" json:"userBalance,omitempty"`
	IosBalance           int32    `protobuf:"varint,5,opt,name=iosBalance,proto3" json:"iosBalance,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBracket) Reset()         { *m = UserBracket{} }
func (m *UserBracket) String() string { return proto.CompactTextString(m) }
func (*UserBracket) ProtoMessage()    {}
func (*UserBracket) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserBracket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBracket.Unmarshal(m, b)
}
func (m *UserBracket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBracket.Marshal(b, m, deterministic)
}
func (m *UserBracket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBracket.Merge(m, src)
}
func (m *UserBracket) XXX_Size() int {
	return xxx_messageInfo_UserBracket.Size(m)
}
func (m *UserBracket) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBracket.DiscardUnknown(m)
}

var xxx_messageInfo_UserBracket proto.InternalMessageInfo

func (m *UserBracket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserBracket) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserBracket) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserBracket) GetUserBalance() int32 {
	if m != nil {
		return m.UserBalance
	}
	return 0
}

func (m *UserBracket) GetIosBalance() int32 {
	if m != nil {
		return m.IosBalance
	}
	return 0
}

func (m *UserBracket) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Response struct {
	Data                 []*UserBracket `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32          `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32          `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []*UserBracket {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *Response) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*UserBracket)(nil), "user.UserBracket")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x69, 0x9b, 0x34, 0xe9, 0xa4, 0x5b, 0xc0, 0x42, 0xc8, 0x2c, 0x12, 0x44, 0x91, 0x10,
	0x15, 0x87, 0x3d, 0x2c, 0x6f, 0xb0, 0xda, 0x0b, 0xd7, 0x2c, 0x9c, 0x38, 0x44, 0x26, 0x9e, 0x05,
	0xab, 0x69, 0x1c, 0x32, 0x0e, 0x55, 0xf7, 0xa5, 0x78, 0x3c, 0xae, 0xc8, 0xe3, 0xb4, 0x0a, 0xe2,
	0xb0, 0xa7, 0xcc, 0xff, 0xcd, 0x4c, 0xec, 0xf9, 0x33, 0x01, 0x18, 0x08, 0xfb, 0xab, 0xae, 0xb7,
	0xce, 0x8a, 0xc8, 0xc7, 0xc5, 0x9f, 0x39, 0x24, 0x25, 0xfe, 0x1c, 0x90, 0x9c, 0xd8, 0xc0, 0xdc,
	0x68, 0xb9, 0xca, 0x67, 0xdb, 0xb8, 0x9c, 0x1b, 0x2d, 0x9e, 0xc1, 0x62, 0x30, 0x5a, 0x66, 0x0c,
	0x7c, 0x28, 0x04, 0x44, 0xad, 0xda, 0xa3, 0x9c, 0xe5, 0xb3, 0xed, 0xaa, 0xe4, 0xd8, 0x33, 0x77,
	0xec, 0x50, 0xce, 0x03, 0xf3, 0xb1, 0x78, 0x01, 0xf1, 0x2f, 0xd5, 0x0c, 0x28, 0x17, 0x0c, 0x83,
	0x10, 0x6f, 0x21, 0xab, 0x7b, 0x54, 0x0e, 0x2b, 0x67, 0xf6, 0x28, 0x23, 0xce, 0x41, 0x40, 0x9f,
	0xcd, 0x9e, 0x0b, 0x86, 0x4e, 0x9f, 0x0b, 0xe2, 0x50, 0x10, 0x10, 0x17, 0xbc, 0x86, 0x95, 0xa1,
	0x4a, 0x63, 0x83, 0x0e, 0xe5, 0x92, 0xef, 0x95, 0x1a, 0xba, 0x65, 0xed, 0x2f, 0xd2, 0xa9, 0xef,
	0x28, 0x13, 0xe6, 0x1c, 0xfb, 0x06, 0xff, 0xac, 0xc8, 0x3c, 0xa0, 0x4c, 0x43, 0x83, 0x07, 0x77,
	0xe6, 0x01, 0xc5, 0x4b, 0x58, 0xf6, 0xa8, 0xc8, 0xb6, 0x72, 0xcd, 0x27, 0x8d, 0xca, 0x73, 0x72,
	0xca, 0x0d, 0x24, 0x2f, 0xb8, 0x63, 0x54, 0xe2, 0x15, 0xa4, 0x07, 0xdb, 0xef, 0xa8, 0x32, 0x5a,
	0x6e, 0xb8, 0x23, 0x61, 0xfd, 0x49, 0xf3, 0x68, 0x8d, 0xa5, 0xa1, 0xc7, 0x4a, 0xab, 0xa3, 0x7c,
	0x3a, 0x8e, 0x16, 0xd0, 0xad, 0x3a, 0x7a, 0x2f, 0x8d, 0x26, 0x09, 0xf9, 0xc2, 0x7b, 0x69, 0x34,
	0x15, 0xbf, 0x67, 0x90, 0x7d, 0x21, 0xec, 0x6f, 0x7a, 0x55, 0xef, 0xf0, 0x7f, 0xf7, 0x2f, 0x21,
	0x6d, 0x4d, 0xbd, 0x63, 0xbf, 0x83, 0xb7, 0x67, 0xed, 0x73, 0xfe, 0xeb, 0x71, 0x2e, 0x58, 0x7c,
	0xd6, 0x22, 0x87, 0xcc, 0xc7, 0x37, 0xaa, 0x51, 0x6d, 0x1d, 0x5c, 0x8e, 0xcb, 0x29, 0x12, 0x6f,
	0x00, 0x8c, 0xa5, 0x53, 0x41, 0xcc, 0x05, 0x13, 0x32, 0x99, 0x3f, 0x99, 0xce, 0x5f, 0xec, 0x20,
	0x2d, 0x91, 0x3a, 0xdb, 0x12, 0x8a, 0x77, 0x10, 0x69, 0xe5, 0x94, 0x5c, 0xe7, 0x8b, 0x6d, 0x76,
	0xfd, 0xfc, 0x8a, 0x17, 0x6b, 0x32, 0x4e, 0xc9, 0x69, 0x51, 0xc0, 0x5a, 0xdd, 0xdf, 0x63, 0xed,
	0x50, 0x97, 0xf6, 0x40, 0xe3, 0x2e, 0xfd, 0xc3, 0xfc, 0xb2, 0x38, 0xeb, 0x54, 0x33, 0xba, 0x1d,
	0xc4, 0xf5, 0x57, 0x88, 0xfc, 0xeb, 0xc4, 0x7b, 0x88, 0xee, 0x7e, 0xd8, 0x83, 0xb8, 0x08, 0x47,
	0x8c, 0xbb, 0x7a, 0xb9, 0x39, 0xc9, 0x70, 0x9f, 0xe2, 0x89, 0xf8, 0x00, 0xc9, 0xe8, 0xf7, 0xa3,
	0xb5, 0xdf, 0x96, 0xfc, 0x0b, 0x7c, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x17, 0xc4, 0xe0,
	0x10, 0x03, 0x00, 0x00,
}
