// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,11,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDelete             int32    `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Reason               string   `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	WorksId              string   `protobuf:"bytes,14,opt,name=Works_id,json=WorksId,proto3" json:"Works_id,omitempty"`
	Ids                  []int32  `protobuf:"varint,10,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Request) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Request) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Request) GetIsDelete() int32 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *Request) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Response struct {
	Data                 []*Response_Notify `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32              `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32              `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []*Response_Notify {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *Response) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Response_Notify struct {
	Id int32 `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	//        string name = 1;
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	UserBalance          int32    `protobuf:"varint,4,opt,name=UserBalance,proto3" json:"UserBalance,omitempty"`
	IosBalance           int32    `protobuf:"varint,5,opt,name=IosBalance,proto3" json:"IosBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Notify) Reset()         { *m = Response_Notify{} }
func (m *Response_Notify) String() string { return proto.CompactTextString(m) }
func (*Response_Notify) ProtoMessage()    {}
func (*Response_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}

func (m *Response_Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Notify.Unmarshal(m, b)
}
func (m *Response_Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Notify.Marshal(b, m, deterministic)
}
func (m *Response_Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Notify.Merge(m, src)
}
func (m *Response_Notify) XXX_Size() int {
	return xxx_messageInfo_Response_Notify.Size(m)
}
func (m *Response_Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Notify proto.InternalMessageInfo

func (m *Response_Notify) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response_Notify) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Response_Notify) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Response_Notify) GetUserBalance() int32 {
	if m != nil {
		return m.UserBalance
	}
	return 0
}

func (m *Response_Notify) GetIosBalance() int32 {
	if m != nil {
		return m.IosBalance
	}
	return 0
}

type AuditLogResponse struct {
	Data                 []*AuditLogResponse_Notify `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32                      `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32                      `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AuditLogResponse) Reset()         { *m = AuditLogResponse{} }
func (m *AuditLogResponse) String() string { return proto.CompactTextString(m) }
func (*AuditLogResponse) ProtoMessage()    {}
func (*AuditLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *AuditLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogResponse.Unmarshal(m, b)
}
func (m *AuditLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogResponse.Marshal(b, m, deterministic)
}
func (m *AuditLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogResponse.Merge(m, src)
}
func (m *AuditLogResponse) XXX_Size() int {
	return xxx_messageInfo_AuditLogResponse.Size(m)
}
func (m *AuditLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogResponse proto.InternalMessageInfo

func (m *AuditLogResponse) GetData() []*AuditLogResponse_Notify {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuditLogResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *AuditLogResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AuditLogResponse_Notify struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	WorksId              string   `protobuf:"bytes,3,opt,name=works_id,json=worksId,proto3" json:"works_id,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditLogResponse_Notify) Reset()         { *m = AuditLogResponse_Notify{} }
func (m *AuditLogResponse_Notify) String() string { return proto.CompactTextString(m) }
func (*AuditLogResponse_Notify) ProtoMessage()    {}
func (*AuditLogResponse_Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2, 0}
}

func (m *AuditLogResponse_Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogResponse_Notify.Unmarshal(m, b)
}
func (m *AuditLogResponse_Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogResponse_Notify.Marshal(b, m, deterministic)
}
func (m *AuditLogResponse_Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogResponse_Notify.Merge(m, src)
}
func (m *AuditLogResponse_Notify) XXX_Size() int {
	return xxx_messageInfo_AuditLogResponse_Notify.Size(m)
}
func (m *AuditLogResponse_Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogResponse_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogResponse_Notify proto.InternalMessageInfo

func (m *AuditLogResponse_Notify) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuditLogResponse_Notify) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuditLogResponse_Notify) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

func (m *AuditLogResponse_Notify) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *AuditLogResponse_Notify) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuditLogResponse_Notify) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_Notify)(nil), "Response.Notify")
	proto.RegisterType((*AuditLogResponse)(nil), "AuditLogResponse")
	proto.RegisterType((*AuditLogResponse_Notify)(nil), "AuditLogResponse.Notify")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0xd2, 0xa4, 0x4d, 0x6f, 0x4b, 0x55, 0x2c, 0x84, 0xbc, 0x22, 0x20, 0x8a, 0x78, 0xe8,
	0x03, 0x2a, 0xd2, 0xf8, 0x02, 0xd0, 0x5e, 0x26, 0x21, 0x1e, 0x32, 0x10, 0x8f, 0x95, 0xa9, 0x6f,
	0x87, 0xb5, 0xb4, 0x0e, 0xb1, 0x43, 0xd9, 0x7e, 0x02, 0x89, 0x8f, 0xe3, 0x77, 0x40, 0xbe, 0x4e,
	0xb2, 0xb6, 0x13, 0x8f, 0x7b, 0xea, 0x3d, 0xe7, 0x1e, 0x37, 0xd6, 0x39, 0xc7, 0x00, 0xb5, 0xc1,
	0x6a, 0x51, 0x56, 0xda, 0xea, 0xec, 0x4f, 0x08, 0x83, 0x1c, 0xbf, 0xd7, 0x68, 0x2c, 0x9b, 0x40,
	0xa8, 0x24, 0x1f, 0xa6, 0xc1, 0x3c, 0xce, 0x43, 0x25, 0xd9, 0x14, 0x7a, 0xb5, 0x92, 0x7c, 0x44,
	0x84, 0x1b, 0x19, 0x83, 0x68, 0x2b, 0x36, 0xc8, 0x83, 0x34, 0x98, 0x0f, 0x73, 0x9a, 0x1d, 0x67,
	0x6f, 0x4a, 0xe4, 0xa1, 0xe7, 0xdc, 0xcc, 0x9e, 0x40, 0xfc, 0x43, 0x14, 0x35, 0xf2, 0x1e, 0x91,
	0x1e, 0xb0, 0x97, 0x30, 0x5a, 0x55, 0x28, 0x2c, 0x2e, 0xad, 0xda, 0x20, 0x8f, 0x68, 0x07, 0x9e,
	0xfa, 0xa4, 0x36, 0x24, 0xa8, 0x4b, 0xd9, 0x09, 0x62, 0x2f, 0xf0, 0x14, 0x09, 0x9e, 0xc1, 0x50,
	0x99, 0xa5, 0xc4, 0x02, 0x2d, 0xf2, 0x3e, 0xdd, 0x2b, 0x51, 0xe6, 0x9c, 0xb0, 0xbb, 0x48, 0x29,
	0xae, 0x90, 0x0f, 0x88, 0xa7, 0xd9, 0x1d, 0x70, 0xbf, 0x4b, 0xa3, 0x6e, 0x91, 0x27, 0xfe, 0x80,
	0x23, 0x2e, 0xd5, 0x2d, 0xb2, 0xa7, 0xd0, 0xaf, 0x50, 0x18, 0xbd, 0xe5, 0x63, 0xfa, 0x52, 0x83,
	0x1c, 0x6f, 0xac, 0xb0, 0xb5, 0xe1, 0x8f, 0xe8, 0x44, 0x83, 0xd8, 0x29, 0x24, 0x5f, 0x74, 0x75,
	0x6d, 0x96, 0x4a, 0xf2, 0x09, 0x9d, 0x18, 0x10, 0xbe, 0x20, 0xab, 0x94, 0x34, 0x1c, 0xd2, 0x9e,
	0xb3, 0x4a, 0x49, 0x93, 0xfd, 0x0d, 0x20, 0xc9, 0xd1, 0x94, 0x7a, 0x6b, 0x90, 0xbd, 0x82, 0x48,
	0x0a, 0x2b, 0xf8, 0x38, 0xed, 0xcd, 0x47, 0x67, 0xd3, 0x45, 0xbb, 0x58, 0x7c, 0xd4, 0x56, 0xad,
	0x6f, 0x72, 0xda, 0xb2, 0x0c, 0xc6, 0x62, 0xbd, 0xc6, 0x95, 0x45, 0x99, 0xeb, 0x9d, 0x69, 0x8c,
	0x3f, 0xe0, 0x9c, 0xb3, 0x56, 0x5b, 0x51, 0x34, 0x57, 0xf3, 0x60, 0xf6, 0x3b, 0x80, 0xbe, 0xff,
	0xab, 0x7b, 0x21, 0xce, 0x20, 0xd9, 0xaa, 0xd5, 0x35, 0xc5, 0xe6, 0x23, 0xea, 0xb0, 0xdb, 0x7d,
	0x36, 0x58, 0xd1, 0xce, 0x27, 0xd5, 0x61, 0x96, 0xc2, 0xc8, 0xcd, 0xef, 0x45, 0x21, 0xb6, 0x2b,
	0x1f, 0x56, 0x9c, 0xef, 0x53, 0xec, 0x05, 0xc0, 0x85, 0x36, 0xad, 0x20, 0x26, 0xc1, 0x1e, 0x93,
	0xfd, 0x0a, 0x61, 0xfa, 0xae, 0x96, 0xca, 0x7e, 0xd0, 0x57, 0x9d, 0x13, 0xaf, 0x0f, 0x9c, 0xe0,
	0x8b, 0x63, 0xc1, 0x83, 0x39, 0x12, 0x1c, 0xd7, 0x3a, 0xbc, 0xab, 0xf5, 0x29, 0x24, 0xbb, 0x36,
	0x58, 0xef, 0xc3, 0x60, 0xd7, 0x04, 0x7b, 0xd7, 0x91, 0xe8, 0xa0, 0x23, 0x6d, 0xeb, 0xe3, 0xbd,
	0xd6, 0x1f, 0xf5, 0xbb, 0x7f, 0xdc, 0xef, 0xb3, 0x9f, 0x10, 0x39, 0x03, 0xd9, 0x73, 0x88, 0x2e,
	0xbf, 0xe9, 0x1d, 0x4b, 0x16, 0xcd, 0xd3, 0x9b, 0x0d, 0xbb, 0x4a, 0x64, 0x27, 0x2c, 0x85, 0xc1,
	0xaa, 0xd0, 0xa6, 0xae, 0xf0, 0x7f, 0x8a, 0x37, 0x30, 0x69, 0x8d, 0x3b, 0x47, 0x2b, 0x54, 0xb1,
	0x27, 0x7c, 0x7c, 0xcf, 0xd3, 0xec, 0xe4, 0x6b, 0x9f, 0x5e, 0xfb, 0xdb, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x9c, 0xae, 0xf2, 0xf7, 0xfb, 0x03, 0x00, 0x00,
}
