// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userVipService.proto

package userVip

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserVipService service

type UserVipService interface {
	UserVipInfo(ctx context.Context, in *UserVipInfoRequest, opts ...client.CallOption) (*UserVipInfoResponse, error)
}

type userVipService struct {
	c    client.Client
	name string
}

func NewUserVipService(name string, c client.Client) UserVipService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "userVip"
	}
	return &userVipService{
		c:    c,
		name: name,
	}
}

func (c *userVipService) UserVipInfo(ctx context.Context, in *UserVipInfoRequest, opts ...client.CallOption) (*UserVipInfoResponse, error) {
	req := c.c.NewRequest(c.name, "UserVipService.userVipInfo", in)
	out := new(UserVipInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserVipService service

type UserVipServiceHandler interface {
	UserVipInfo(context.Context, *UserVipInfoRequest, *UserVipInfoResponse) error
}

func RegisterUserVipServiceHandler(s server.Server, hdlr UserVipServiceHandler, opts ...server.HandlerOption) error {
	type userVipService interface {
		UserVipInfo(ctx context.Context, in *UserVipInfoRequest, out *UserVipInfoResponse) error
	}
	type UserVipService struct {
		userVipService
	}
	h := &userVipServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserVipService{h}, opts...))
}

type userVipServiceHandler struct {
	UserVipServiceHandler
}

func (h *userVipServiceHandler) UserVipInfo(ctx context.Context, in *UserVipInfoRequest, out *UserVipInfoResponse) error {
	return h.UserVipServiceHandler.UserVipInfo(ctx, in, out)
}
