// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: marketContentConf.proto

package marketContentConf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MarketContentConf service

type MarketContentConfService interface {
	Index(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type marketContentConfService struct {
	c    client.Client
	name string
}

func NewMarketContentConfService(name string, c client.Client) MarketContentConfService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "marketContentConf"
	}
	return &marketContentConfService{
		c:    c,
		name: name,
	}
}

func (c *marketContentConfService) Index(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MarketContentConf.Index", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MarketContentConf service

type MarketContentConfHandler interface {
	Index(context.Context, *Request, *Response) error
}

func RegisterMarketContentConfHandler(s server.Server, hdlr MarketContentConfHandler, opts ...server.HandlerOption) error {
	type marketContentConf interface {
		Index(ctx context.Context, in *Request, out *Response) error
	}
	type MarketContentConf struct {
		marketContentConf
	}
	h := &marketContentConfHandler{hdlr}
	return s.Handle(s.NewHandler(&MarketContentConf{h}, opts...))
}

type marketContentConfHandler struct {
	MarketContentConfHandler
}

func (h *marketContentConfHandler) Index(ctx context.Context, in *Request, out *Response) error {
	return h.MarketContentConfHandler.Index(ctx, in, out)
}
