// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bank.proto

package bank

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId               int32    `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetSiteId() int32 {
	if m != nil {
		return m.SiteId
	}
	return 0
}

func (m *Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Response struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId               int32    `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Card                 string   `protobuf:"bytes,5,opt,name=card,proto3" json:"card,omitempty"`
	Tel                  string   `protobuf:"bytes,6,opt,name=tel,proto3" json:"tel,omitempty"`
	FianacialContact     string   `protobuf:"bytes,7,opt,name=fianacialContact,proto3" json:"fianacialContact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6371916d5cb63b4, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetSiteId() int32 {
	if m != nil {
		return m.SiteId
	}
	return 0
}

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Response) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *Response) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *Response) GetFianacialContact() string {
	if m != nil {
		return m.FianacialContact
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("bank.proto", fileDescriptor_a6371916d5cb63b4) }

var fileDescriptor_a6371916d5cb63b4 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0xd0, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x60, 0xb3, 0x4d, 0x77, 0xdb, 0x39, 0x48, 0x99, 0x83, 0x0c, 0x82, 0x50, 0x16, 0x84,
	0xe2, 0x61, 0x0f, 0xfa, 0x06, 0x7a, 0xea, 0x35, 0x3e, 0xc1, 0x34, 0x89, 0x18, 0x5a, 0x92, 0xda,
	0xcc, 0xe2, 0x9b, 0xf9, 0x7c, 0xe2, 0xb0, 0x7b, 0xf2, 0xd8, 0xdb, 0xff, 0x7f, 0x81, 0xc0, 0xfc,
	0x00, 0x07, 0xce, 0xc7, 0xe1, 0x7c, 0x29, 0x52, 0xfa, 0x3d, 0x74, 0x2e, 0x7e, 0x8d, 0xb1, 0x0a,
	0xde, 0x42, 0x93, 0x02, 0x99, 0xad, 0xd9, 0x2d, 0x5d, 0x93, 0x02, 0xde, 0x41, 0x5b, 0x93, 0xc4,
	0x7d, 0xa0, 0x46, 0x6d, 0x6a, 0xea, 0xc2, 0x32, 0x56, 0x5a, 0x4c, 0xae, 0xad, 0xff, 0x31, 0xb0,
	0x72, 0xb1, 0x9e, 0x4b, 0xae, 0xf1, 0xda, 0xcf, 0x90, 0xa0, 0x63, 0xef, 0xcb, 0x98, 0x85, 0xec,
	0xd6, 0xec, 0xd6, 0x6e, 0xae, 0x88, 0x60, 0x3d, 0x5f, 0x02, 0x2d, 0x95, 0x35, 0xe3, 0x06, 0x16,
	0x12, 0x4f, 0xd4, 0x2a, 0xfd, 0x45, 0x7c, 0x82, 0xcd, 0x47, 0xe2, 0xcc, 0x3e, 0xf1, 0xe9, 0xad,
	0x64, 0x61, 0x2f, 0xd4, 0xe9, 0xf3, 0x3f, 0x7f, 0x7e, 0x04, 0xfb, 0xca, 0xf9, 0x88, 0x0f, 0x60,
	0xdf, 0x3f, 0xcb, 0x37, 0xae, 0x86, 0x69, 0x92, 0xfb, 0xf5, 0x30, 0x1f, 0xd4, 0xdf, 0x1c, 0x5a,
	0x5d, 0xec, 0xe5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x87, 0xb8, 0xbd, 0x31, 0x3f, 0x01, 0x00, 0x00,
}
