// Code generated by protoc-gen-go. DO NOT EDIT.
// source: witnesses.proto

package works_witnesses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WitnessesRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Uid                  int32    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	WorksId              string   `protobuf:"bytes,5,opt,name=worksId,proto3" json:"worksId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WitnessesRequest) Reset()         { *m = WitnessesRequest{} }
func (m *WitnessesRequest) String() string { return proto.CompactTextString(m) }
func (*WitnessesRequest) ProtoMessage()    {}
func (*WitnessesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfaa1fdb06a6ede2, []int{0}
}

func (m *WitnessesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WitnessesRequest.Unmarshal(m, b)
}
func (m *WitnessesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WitnessesRequest.Marshal(b, m, deterministic)
}
func (m *WitnessesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessesRequest.Merge(m, src)
}
func (m *WitnessesRequest) XXX_Size() int {
	return xxx_messageInfo_WitnessesRequest.Size(m)
}
func (m *WitnessesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessesRequest proto.InternalMessageInfo

func (m *WitnessesRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *WitnessesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *WitnessesRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *WitnessesRequest) GetWorksId() string {
	if m != nil {
		return m.WorksId
	}
	return ""
}

type WitnessesResponse struct {
	Data                 []*Witness `protobuf:"bytes,12,rep,name=data,proto3" json:"data,omitempty"`
	AffectedRows         int32      `protobuf:"varint,11,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	Total                int32      `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WitnessesResponse) Reset()         { *m = WitnessesResponse{} }
func (m *WitnessesResponse) String() string { return proto.CompactTextString(m) }
func (*WitnessesResponse) ProtoMessage()    {}
func (*WitnessesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfaa1fdb06a6ede2, []int{1}
}

func (m *WitnessesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WitnessesResponse.Unmarshal(m, b)
}
func (m *WitnessesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WitnessesResponse.Marshal(b, m, deterministic)
}
func (m *WitnessesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessesResponse.Merge(m, src)
}
func (m *WitnessesResponse) XXX_Size() int {
	return xxx_messageInfo_WitnessesResponse.Size(m)
}
func (m *WitnessesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessesResponse proto.InternalMessageInfo

func (m *WitnessesResponse) GetData() []*Witness {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WitnessesResponse) GetAffectedRows() int32 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

func (m *WitnessesResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Witness struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	EventId              string   `protobuf:"bytes,3,opt,name=eventId,proto3" json:"eventId,omitempty"`
	IsLiteEvent          int32    `protobuf:"varint,4,opt,name=isLiteEvent,proto3" json:"isLiteEvent,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Ip                   int64    `protobuf:"varint,7,opt,name=ip,proto3" json:"ip,omitempty"`
	UidEventId           string   `protobuf:"bytes,8,opt,name=uidEventId,proto3" json:"uidEventId,omitempty"`
	CreateTime           string   `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Witness) Reset()         { *m = Witness{} }
func (m *Witness) String() string { return proto.CompactTextString(m) }
func (*Witness) ProtoMessage()    {}
func (*Witness) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfaa1fdb06a6ede2, []int{2}
}

func (m *Witness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Witness.Unmarshal(m, b)
}
func (m *Witness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Witness.Marshal(b, m, deterministic)
}
func (m *Witness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Witness.Merge(m, src)
}
func (m *Witness) XXX_Size() int {
	return xxx_messageInfo_Witness.Size(m)
}
func (m *Witness) XXX_DiscardUnknown() {
	xxx_messageInfo_Witness.DiscardUnknown(m)
}

var xxx_messageInfo_Witness proto.InternalMessageInfo

func (m *Witness) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Witness) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Witness) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Witness) GetIsLiteEvent() int32 {
	if m != nil {
		return m.IsLiteEvent
	}
	return 0
}

func (m *Witness) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Witness) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Witness) GetIp() int64 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *Witness) GetUidEventId() string {
	if m != nil {
		return m.UidEventId
	}
	return ""
}

func (m *Witness) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Witness) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*WitnessesRequest)(nil), "works.witnesses.WitnessesRequest")
	proto.RegisterType((*WitnessesResponse)(nil), "works.witnesses.WitnessesResponse")
	proto.RegisterType((*Witness)(nil), "works.witnesses.Witness")
}

func init() { proto.RegisterFile("witnesses.proto", fileDescriptor_dfaa1fdb06a6ede2) }

var fileDescriptor_dfaa1fdb06a6ede2 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x4e, 0xe3, 0x30,
	0x14, 0x85, 0x27, 0x49, 0xd3, 0x9f, 0x9b, 0xce, 0xb4, 0x73, 0x35, 0x1a, 0x59, 0x5d, 0x40, 0xc8,
	0x2a, 0x0b, 0x94, 0x45, 0x79, 0x86, 0x2e, 0x2a, 0xb1, 0x40, 0x01, 0x89, 0x15, 0x42, 0xa6, 0xbe,
	0x45, 0x16, 0x6d, 0x1c, 0x62, 0x87, 0x22, 0x78, 0x00, 0x5e, 0x1b, 0xc5, 0x71, 0xa3, 0x16, 0x09,
	0x56, 0xf1, 0xf9, 0x72, 0xe2, 0xe3, 0x13, 0x5f, 0x98, 0xec, 0xa4, 0x29, 0x48, 0x6b, 0xd2, 0x59,
	0x59, 0x29, 0xa3, 0x70, 0xb2, 0x53, 0xd5, 0x93, 0xce, 0x3a, 0x9c, 0x14, 0x30, 0xbd, 0xdd, 0x8b,
	0x9c, 0x9e, 0x6b, 0xd2, 0x06, 0x11, 0x7a, 0x25, 0x7f, 0x24, 0xe6, 0xc5, 0x5e, 0x1a, 0xe6, 0x76,
	0x8d, 0x33, 0x18, 0x36, 0xcf, 0x6b, 0xf9, 0x46, 0xcc, 0xb7, 0xbc, 0xd3, 0x38, 0x85, 0xa0, 0x96,
	0x82, 0xf5, 0x2c, 0x6e, 0x96, 0xc8, 0x60, 0x60, 0x83, 0x96, 0x82, 0x85, 0xb1, 0x97, 0x8e, 0xf2,
	0xbd, 0x4c, 0xde, 0xe1, 0xef, 0x41, 0x9e, 0x2e, 0x55, 0xa1, 0x09, 0xcf, 0xa1, 0x27, 0xb8, 0xe1,
	0x6c, 0x1c, 0x07, 0x69, 0x34, 0x67, 0xd9, 0x97, 0x43, 0x66, 0xee, 0x8b, 0xdc, 0xba, 0x30, 0x81,
	0x31, 0x5f, 0xaf, 0x69, 0x65, 0x48, 0xe4, 0x6a, 0xa7, 0x59, 0x64, 0x73, 0x8f, 0x18, 0xfe, 0x83,
	0xd0, 0x28, 0xc3, 0x37, 0xec, 0xb7, 0x7d, 0xd9, 0x8a, 0xe4, 0xc3, 0x87, 0x81, 0xdb, 0x0b, 0xff,
	0x80, 0x2f, 0x85, 0xab, 0xe8, 0x4b, 0xb1, 0x2f, 0xe1, 0x1f, 0x95, 0xa0, 0x17, 0x2a, 0xcc, 0x52,
	0xb0, 0xa0, 0x2d, 0xe1, 0x24, 0xc6, 0x10, 0x49, 0x7d, 0x29, 0x0d, 0x2d, 0x1a, 0xe0, 0x8a, 0x1f,
	0x22, 0x9b, 0x2f, 0xcd, 0x86, 0x5c, 0xfd, 0x56, 0xe0, 0x7f, 0xe8, 0x57, 0xc4, 0xb5, 0x2a, 0x58,
	0xdf, 0x62, 0xa7, 0xec, 0x59, 0x4a, 0x36, 0x88, 0xbd, 0x34, 0xc8, 0x7d, 0x59, 0xe2, 0x09, 0x40,
	0x2d, 0xc5, 0xc2, 0x85, 0x0f, 0xad, 0xf7, 0x80, 0xe0, 0x29, 0x44, 0xab, 0x8a, 0xb8, 0xa1, 0x7b,
	0x23, 0xb7, 0xc4, 0x46, 0xad, 0xa1, 0x45, 0x37, 0x72, 0x4b, 0x8d, 0xa1, 0x2e, 0x45, 0x67, 0x00,
	0xb7, 0x83, 0x45, 0x8d, 0x61, 0x7e, 0x07, 0xa3, 0xee, 0x1a, 0xf0, 0x0a, 0xc2, 0x65, 0x21, 0xe8,
	0x15, 0xcf, 0xbe, 0xfb, 0xf3, 0xdd, 0x6c, 0xcc, 0x92, 0x9f, 0x2c, 0xed, 0x75, 0x26, 0xbf, 0x1e,
	0xfa, 0x76, 0xda, 0x2e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x2e, 0xab, 0x6a, 0x80, 0x02,
	0x00, 0x00,
}
